// Generated from Notion on 2026-08-15. Update via the Notion sync workflow; do not hand-edit case content.

export interface NotionCaseRecord {
  id: number;
  notionPageId: string;
  name: string;
  patientName: string;
  ageSex: string;
  arrival: string;
  method: string;
  expectedTriage: string;
  clinicalZones: string;
  destination: string;
  opeAg: string;
  overview: string;
  chiefComplaint: string;
  rescueVitals: string;
  primaryTriageFindings: string;
  initialVitals: string;
  exam: string;
  tests: string;
  bloodGas: string;
  specimenTests: string;
  imaging: string;
  treatment: string;
  additionalEvent: string;
  controllerInstruction: string;
  controllerChecklist: string;
  actingPoints: string;
  focus: string;
  learningPoints: string;
  branchConditions: string;
  postErSetting: string;
  moulage: string;
  originalId: string;
  originalCase: string;
}

export interface ControllerCaseRecord {
  patientId: number;
  status: string;
  arrivalGuide: string;
  arrivalWindow: string;
  careGuide: string;
  careWindow: string;
  escalationGuide: string;
  escalationWindow: string;
  mediaGuide: string;
  notes: string;
}

export const notionCases: NotionCaseRecord[] = [
  {
    "id": 1,
    "notionPageId": "a1ae1849-3b18-4aa5-887d-1eb29d6d17ce",
    "name": "左血気胸・多発肋骨骨折",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:05",
    "method": "救急車",
    "expectedTriage": "赤",
    "clinicalZones": "[\"救外\"]",
    "destination": "[\"ICU\"]",
    "opeAg": "[\"OPE\"]",
    "overview": "張碓多重衝突事故の第1波。救急車搬送の赤症例として救外へ直行。張碓付近のマイクロバス多重衝突で、座席の肘掛けに左胸部を強打。左多発肋骨骨折、左外傷性血気胸。胸腔ドレーン挿入後は初期排液1000mL、その後150mL/hで持続する。呼吸器外科へコンサルトし、ICUへ入室して経過観察とする。ICU入室後に排液量・出血量が増大し、ICUから手術室へ搬送して開胸止血を行う症例。",
    "chiefComplaint": "左胸部痛・呼吸困難",
    "rescueVitals": "BP 78/52、HR 122、SpO2 85%RA→酸素後90%、RR 40",
    "primaryTriageFindings": "左胸部痛、呼吸困難、SpO2低下、左呼吸音減弱、顔面蒼白",
    "initialVitals": "BP 78/52、HR 122、SpO2 85%RA→酸素後90%、RR 40",
    "exam": "左胸部圧痛著明、左呼吸音減弱、顔面蒼白、呼吸苦著明。",
    "tests": "CT: 左血気胸、多発肋骨骨折。",
    "bloodGas": "〇",
    "specimenTests": "〇",
    "imaging": "〇",
    "treatment": "高流量酸素、胸腔ドレーン、輸液・輸血、呼吸器外科コンサルト。ICU入室を調整する。",
    "additionalEvent": "救急車①で搬入する赤症例。直後（10:08）に症例2が乗用車で来院するため、初療ベッド配分と赤症例の優先順位判断を促す。胸腔ドレーン後は排液150mL/hで持続するため呼吸器外科へコンサルトし、ICU入室を調整する。",
    "controllerInstruction": "救急車①で搬入。左血気胸・多発肋骨骨折、BP 78/52、HR 122、SpO2 85%RA→酸素後90%、RR 40を提示する。胸腔ドレーンで初期排液1000mL、その後150mL/hの持続出血を提示。輸血とドレーン管理を継続し、呼吸器外科へコンサルトしてICU入室を調整させる。",
    "controllerChecklist": "□ 高流量酸素と気道・呼吸の評価\n□ 胸腔ドレーンを留置し初期排液1000mLと時間排液150mL/hを記録\n□ 早期に輸血（大量輸血プロトコル）を開始\n□ 150mL/hの持続出血を受けて呼吸器外科へコンサルト\n□ ICU入室を本部・ICUへ依頼",
    "actingPoints": "左胸部を押さえ、浅く速い呼吸。会話は短い単語のみ。横になることを嫌がり座位を希望。",
    "focus": "胸部外傷、血気胸、胸腔ドレーン、150mL/h持続出血、呼吸器外科コンサルト、ICU入室調整",
    "learningPoints": "初期排液1000mL後に150mL/hの持続出血がある場合、直ちに手術と決め打ちせず、呼吸器外科へコンサルトし、ドレーン管理・輸血・呼吸循環の反復評価を行う。\n災害時は呼吸器外科・ICU・手術室を段階的かつ早期に連携させる。",
    "branchConditions": "【必須処置】\n初療開始から15分以内に必要な対応を選択\n・モニター装着\n・酸素投与\n・末梢ルート確保\n・急速輸液\n・輸血\n・胸腔ドレーン留置\n・呼吸器外科\n・ICU\n【対応できた場合】\n酸素化・血圧が一旦安定し、ICUへ搬送\n【一つでも対応できなかった場合】\n持続出血が増え、血圧60台・脈拍140以上・換気困難へ悪化",
    "postErSetting": "ICU入室後、胸腔ドレーン排液量・出血量が増大し、循環が悪化する。ICUから手術室へ搬送して開胸止血術を行い、術後はICU管理を継続する。",
    "moulage": "",
    "originalId": "93",
    "originalCase": "[\"https://app.notion.com/7833006626894ec8a33b5b9b4fff12fc\"]"
  },
  {
    "id": 2,
    "notionPageId": "8c230ee1-f582-40f5-87b3-b8bf7a5fdb1f",
    "name": "不安定型骨盤骨折",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:08",
    "method": "乗用車",
    "expectedTriage": "赤",
    "clinicalZones": "[\"救外\"]",
    "destination": "[\"ICU\",\"EU\"]",
    "opeAg": "[\"AG\"]",
    "overview": "張碓多重衝突事故。乗用車1で直接搬送。歩行可能に見えたが不安定型骨盤骨折のショックで、トリアージアップにより救外へ直接誘導を要する。張碓付近のマイクロバス多重衝突で、車内で体幹部を強打。通りかかった別の乗用車で来院。左骨盤部痛、顔色不良、ショック状態。不安定型骨盤骨折。骨盤固定・輸血のうえAG室でTAEを行うが、TAE後も血圧が不安定で輸血を継続し、ICU入室となる。",
    "chiefComplaint": "左骨盤部痛",
    "rescueVitals": "",
    "primaryTriageFindings": "歩行: 歩行不可扱い（または歩行可能に見えても立位保持困難）。呼吸: RR 30。循環: 脈拍数140、橈骨動脈触知不良、冷汗あり。意識: JCS30、簡単な指示に従えない",
    "initialVitals": "BP 74/42、HR 140、SpO2 94%RA、RR 30",
    "exam": "顔面蒼白、冷汗著明、左骨盤部圧痛・変形、骨盤動揺性あり。",
    "tests": "骨盤X線/CT: 不安定型骨盤骨折。",
    "bloodGas": "〇",
    "specimenTests": "〇",
    "imaging": "〇",
    "treatment": "骨盤バインダー固定、輸液・輸血、TAE（AG）による止血。",
    "additionalEvent": "乗用車1で来院。一見歩けそうに見えるが骨盤骨折によるショックで、トリアージアップして救外ゾーンへ直接誘導する判断を促す。",
    "controllerInstruction": "乗用車1。START一次では過小評価されやすいが、脈拍を速く設定し、橈骨動脈触知不良/HR 140、JCS30、冷汗を付与して赤へアップさせる。骨盤バインダー装着、輸液・輸血、TAE／手術の要否相談を促す。",
    "controllerChecklist": "□ 歩行可能に見えても赤へトリアージアップし救外へ誘導\n□ 骨盤バインダーを早期に装着\n□ 骨盤動揺性の反復診察を避ける\n□ 輸液・輸血（大量輸血プロトコル）を開始\n□ AG室へTAEを依頼し搬送を調整",
    "actingPoints": "刺激で開眼するがすぐ閉眼。意味のある会話は困難。左骨盤部を触られると痛みで反応。",
    "focus": "骨盤骨折、トリアージアップ、出血性ショック、TAE、AG室調整、ICU入室調整",
    "learningPoints": "不安定型骨盤骨折は後腹膜への大量出血源であり、骨盤の外固定が最初にできる止血。\n動揺性の反復診察は再出血を招くため避ける。\n根本止血はTAE、または創外固定・骨盤内パッキング。",
    "branchConditions": "【必須処置】\n初療開始から15分以内に必要な対応を選択\n・骨盤バインダー\n・末梢ルート確保\n・急速輸液\n・輸血\n・放射線科\n【対応できた場合】\n血圧90/60、脈拍85に改善し、放射線科へ搬送\n【一つでも対応できなかった場合】\n血圧60/40、脈拍150へ悪化",
    "postErSetting": "AG室でTAE後、BP 80/50・HR 130、Hb 7.2、乳酸 5.0mmol/Lと循環不安定が持続する。輸血を継続し、再出血・他部位出血を検索する。骨盤内パッキング／創外固定を検討し、ICU入室とする。",
    "moulage": "",
    "originalId": "94",
    "originalCase": "[\"https://app.notion.com/f6a08f2e7ab7421c9b2149dc7fcfd270\"]"
  },
  {
    "id": 3,
    "notionPageId": "6e5e8ca6-5fc4-413f-a434-eed99ea96b46",
    "name": "急性硬膜外血腫",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:14",
    "method": "救急車",
    "expectedTriage": "赤",
    "clinicalZones": "[\"救外\"]",
    "destination": "[\"ICU\",\"EU\"]",
    "opeAg": "[\"OPE\"]",
    "overview": "救急車第2波。頭部外傷として搬入し、CT後に意識レベルが悪化する。張碓付近のマイクロバス多重衝突で、頭部を座席または車内構造物に強打。現場で意識消失後に一時改善。急性硬膜外血腫で手術適応。CT後の意識悪化に対し、気管挿管のうえ緊急開頭血腫除去術を行い、術後はICUまたはEU管理とする。",
    "chiefComplaint": "頭部打撲・一時意識消失",
    "rescueVitals": "来院時 HR 80、BP 160/80、SpO2 100%。初期JCS 10、GCS 11（E3V3M5）。",
    "primaryTriageFindings": "頭部打撲、一時意識消失、瞳孔不同、徐脈・高血圧傾向",
    "initialVitals": "来院時 HR 80、BP 160/80、SpO2 100%。初期JCS 10、GCS 11（E3V3M5）",
    "exam": "歩行不可。",
    "tests": "頭部CT: 急性硬膜外血腫。",
    "bloodGas": "〇",
    "specimenTests": "〇",
    "imaging": "〇",
    "treatment": "気管挿管、緊急開頭血腫除去術。",
    "additionalEvent": "症例19（黄・右大腿骨骨折）と同時到着。救外・軽症ゾーンの振り分けを確認する。",
    "controllerInstruction": "初療時は従命可能、CT結果提示後にGCS低下・瞳孔不同を付与。脳神経外科・手術室へ緊急連絡し、ICU受け入れも同時に調整する。気管挿管のうえ、緊急開頭血腫除去術へ進める。",
    "controllerChecklist": "□ 頭部CTの優先順位を判断し早期に撮影\n□ CT後の意識低下・瞳孔不同・徐脈＋高血圧を認識\n□ GCS≤8でRSIによる気管挿管を実施\n□ 脳神経外科・手術室へ緊急開頭を要請",
    "actingPoints": "来院時はなんとか従命可能。CT後に意識レベル著明低下。痛み刺激に払いのけるのみ、発語なし。",
    "focus": "頭部外傷、CT優先順位、意識悪化、気管挿管、緊急開頭術",
    "learningPoints": "急性硬膜外血腫はlucid intervalの後に急速悪化するため、一時的な意識改善で油断しない。\n徐脈＋高血圧（Cushing現象）と片側瞳孔散大は切迫脳ヘルニアのサイン。\nGCS≤8では気道確保を行い、開頭血腫除去は時間依存性が高い。\n脳神経外科・手術室・ICUを同時に立ち上げる連携。",
    "branchConditions": "【必須処置】\n初療開始から15分以内に必要な対応を選択\n・モニター装着\n・酸素投与\n・気道確保・挿管\n・頭部挙上\n・脳神経外科\n・放射線科\n・手術室/麻酔科\n【対応できた場合】\n気道・酸素化を維持し、緊急手術へ搬送\n【一つでも対応できなかった場合】\n意識・瞳孔が悪化し、脳ヘルニアへ進行",
    "postErSetting": "緊急開頭血腫除去術後はICUまたはEUで管理する。",
    "moulage": "",
    "originalId": "98",
    "originalCase": "[\"https://app.notion.com/7a3db0e670ef429abd7678db12029a96\"]"
  },
  {
    "id": 4,
    "notionPageId": "ab252fce-b2af-48e0-a17e-20bb5af326c6",
    "name": "左外踝骨折",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:15",
    "method": "乗用車",
    "expectedTriage": "黄",
    "clinicalZones": "[\"軽症\"]",
    "destination": "[\"帰宅\"]",
    "opeAg": "",
    "overview": "乗用車1の黄症例。張碓事故後に同乗搬送され、歩行不能で軽症ゾーンへ。左足関節痛で歩行不能。",
    "chiefComplaint": "左足関節痛",
    "rescueVitals": "",
    "primaryTriageFindings": "歩行: 歩行不可。呼吸: 見たまま安定。循環: 脈拍は見たまま、明らかなショックなし。意識: 指示に従える",
    "initialVitals": "実測値で安定",
    "exam": "左外踝圧痛、腫脹。",
    "tests": "X線で左外踝骨折。",
    "bloodGas": "",
    "specimenTests": "",
    "imaging": "〇",
    "treatment": "シーネ固定",
    "additionalEvent": "乗用車1の同乗者として来院。緑症例と同時に軽症ゾーンへ流入し、受付・画像導線を混雑させる。",
    "controllerInstruction": "左足関節腫脹と歩行不可を提示。シーネ固定と画像検査の導線確認を促す。",
    "controllerChecklist": "□ 歩行不能の黄として軽症ゾーンへ誘導\n□ 末梢循環・知覚を確認\n□ X線を依頼し画像導線を確認\n□ シーネ固定と鎮痛を実施",
    "actingPoints": "支えれば立位可。痛み強い。",
    "focus": "歩行不能、シーネ固定、軽症ゾーン運用",
    "learningPoints": "",
    "branchConditions": "【必須処置】\n時間制限なし。以下を完了\n・骨折部の固定\n・鎮痛\n・整形外科\n・放射線科\n【対応できた場合】\n疼痛・腫脹が軽減し、帰宅\n【一つでも対応できなかった場合】\n疼痛・腫脹が増悪し、再評価・処置が必要",
    "postErSetting": "",
    "moulage": "",
    "originalId": "21",
    "originalCase": "[\"https://app.notion.com/3ce2d69c5bbd4904bd429b2e367238e3\"]"
  },
  {
    "id": 5,
    "notionPageId": "01a3b751-d9f1-462d-98b4-806541f23dcd",
    "name": "回転性めまい・歩行不能→シートベルト損傷",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:15",
    "method": "乗用車",
    "expectedTriage": "黄",
    "clinicalZones": "[\"軽症\"]",
    "destination": "[\"ICU\"]",
    "opeAg": "[\"OPE\"]",
    "overview": "乗用車1で来院。シートベルト着用中の衝突で、車内での頭部打撲後にめまいが出現した黄症例として軽症ゾーンへ。遅発性のシートベルト損傷（腸管・腸間膜損傷）。張碓付近の多重衝突事故。シートベルトを着用しており、車内で頭部を打撲した後に回転性めまいと嘔吐が出現して歩行不能。軽症ゾーンで点滴中に腹痛を訴える。（実際に診察はしないが腹部にシートベルト痕あり）　FAST陽性、造影CTで腸管損傷と腸間膜損傷による腹腔内出血が判明し、シートベルト損傷として外科で緊急開腹。術後はICU管理。",
    "chiefComplaint": "回転性めまい・嘔吐",
    "rescueVitals": "",
    "primaryTriageFindings": "歩行: 歩行不能。呼吸: 見たまま安定。循環: 脈拍は見たまま、橈骨動脈触知良好。意識: 指示に従える（閉眼・嘔気あり）",
    "initialVitals": "BP 118/70、HR 88、SpO2 98%RA、RR 16",
    "exam": "強いめまいと眼振あり、その他の身体所見は異常なし。　腹部に少し疼痛あり",
    "tests": "頭部MRI異常なし。腹痛出現後: FAST陽性（モリソン窩・骨盤内に液体貯留）。造影CTで腸間膜からの造影剤漏出と腸管壁の血流不良、腹腔内液体貯留、腹壁のシートベルト痕に一致する皮下血腫。Hb 9.2、乳酸 4.2mmol/L。",
    "bloodGas": "",
    "specimenTests": "",
    "imaging": "〇",
    "treatment": "点滴・鎮痛のうえ経過観察としたが、腹痛出現後にFAST陽性・造影CTで腸管損傷＋腸間膜損傷による腹腔内出血を確認し、シートベルト損傷として外科で緊急開腹（止血・損傷腸管の処理）。",
    "additionalEvent": "乗用車1の同乗者として来院（シートベルト着用）。軽症ゾーンで点滴中（来院約30分後）に腹痛を訴える。\n遅発性に腹部所見が出現するシートベルト損傷（腸管・腸間膜損傷）として、軽症ゾーンから救外への移送、緊急手術とICU入室の手配につなげる判断を促す。",
    "controllerInstruction": "シートベルト着用中の衝突で、車内での頭部打撲後にめまいが出現。神経局在なし、歩行不能、嘔気を提示する。点滴開始後（もしくは診察後）腹痛を訴えさせ、下腹部の帯状皮下出血（シートベルト痕）、BP 86/58・HR 122、FAST陽性、造影CTで腸管損傷＋腸間膜損傷による腹腔内出血を提示。軽症ゾーンから救外への移送、外科コンサルト、緊急開腹とICU入室の調整を判断させる。学生には手術決定が伝えられるまで、かなり強い腹痛を訴え続けさせる。",
    "controllerChecklist": "□ 軽症ゾーンでバイタルと腹部所見を反復評価\n□ 腹痛出現時にFASTを実施し陰性でも再検を検討\n□ 赤へアップトリアージし救外へ移送\n□ 外科コンサルトと造影CTを手配\n□ 緊急開腹の手術室とICU入室を同時に調整",
    "actingPoints": "開眼でめまい増強。「シートベルトしてたから頭は打っていませんが首が強く振られました」と伝える。帰宅させられそうになったらめまいが強くて無理と答える。　 点滴開始直後にめまいは改善するが、コントローラーの合図で腹痛を訴える。以後は手術が決まったと伝えられるまで、かなり強い腹痛を訴え続け、腹部を押さえてぐったりする。",
    "focus": "軽症ゾーンでの再評価、シートベルト痕からの遅発性腸管・腸間膜損傷の想起、FASTの活用、緊急手術の手配、ICU入室調整",
    "learningPoints": "",
    "branchConditions": "【必須処置】\n時間制限なし。以下を完了\n・モニター装着\n・末梢ルート確保\n・急速輸液\n・輸血\n・外科\n・放射線科\n・手術室/麻酔科\n【対応できた場合】\n血圧・脈拍を維持し、腹腔内損傷を確認して緊急手術へ搬送\n【一つでも対応できなかった場合】\n血圧70台・脈拍130、筋性防御が出現し、出血性ショックへ悪化",
    "postErSetting": "",
    "moulage": "",
    "originalId": "22",
    "originalCase": "[\"https://app.notion.com/8e2b3755f9d1409186c850038a5b39b2\"]"
  },
  {
    "id": 6,
    "notionPageId": "ecf470e3-afaf-4658-bec2-d5ced2a53903",
    "name": "前腕擦過傷",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:15",
    "method": "徒歩",
    "expectedTriage": "緑",
    "clinicalZones": "[\"軽症\"]",
    "destination": "[\"帰宅\"]",
    "opeAg": "",
    "overview": "Walk-in第1波の軽症創傷。軽症ゾーン立ち上げ直後に投入。前腕擦過傷と軽い打撲。",
    "chiefComplaint": "前腕擦過傷",
    "rescueVitals": "",
    "primaryTriageFindings": "Walk-in。歩行: 可能。呼吸・脈拍・意識: すべて見たまま安定、指示に従える",
    "initialVitals": "実測値で安定",
    "exam": "前腕浅い擦過傷。",
    "tests": "画像不要。",
    "bloodGas": "",
    "specimenTests": "",
    "imaging": "",
    "treatment": "洗浄/被覆",
    "additionalEvent": "緑患者の受付・帰宅導線確認に使用。",
    "controllerInstruction": "前腕擦過傷のみ、バイタル安定。洗浄・被覆後帰宅可能とする。",
    "controllerChecklist": "特になし",
    "actingPoints": "普通に会話、処置を待てる。\n【Walk-in・軽症】必須処置をしないまま帰宅を促された場合は、「症状が強くて帰られない」「必要な処置をしてください」と訴え、必須処置が終わるまで帰宅しないことをアピールする。",
    "focus": "軽症創傷、洗浄・被覆、帰宅導線",
    "learningPoints": "",
    "branchConditions": "【必須処置】\n時間制限なし。以下を完了\n・創部処置\n【対応できた場合】\n必須処置を完了し、症状が軽減して帰宅\n【一つでも対応できなかった場合】\n症状が強く残り、患者が「なんとかしてください」と訴える",
    "postErSetting": "",
    "moulage": "",
    "originalId": "45",
    "originalCase": "[\"https://app.notion.com/c41650e29bee4b5ea4bffeba89b9a080\"]"
  },
  {
    "id": 7,
    "notionPageId": "5e3b0811-fc35-4477-a9c1-0c88faa78d26",
    "name": "足背切創",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:15",
    "method": "徒歩",
    "expectedTriage": "緑",
    "clinicalZones": "[\"軽症\"]",
    "destination": "[\"帰宅\"]",
    "opeAg": "",
    "overview": "ガラス片による足背切創としてWalk-in第1波に投入。足背浅切創、止血済み。",
    "chiefComplaint": "足背切創",
    "rescueVitals": "",
    "primaryTriageFindings": "Walk-in。歩行: 可能。呼吸・脈拍・意識: すべて見たまま安定、指示に従える",
    "initialVitals": "実測値で安定",
    "exam": "浅い切創、腱損傷なし。",
    "tests": "異物なし。",
    "bloodGas": "",
    "specimenTests": "",
    "imaging": "",
    "treatment": "洗浄/縫合検討",
    "additionalEvent": "創傷処置待ちを軽症ゾーンに発生させる。",
    "controllerInstruction": "止血済み、浅切創、異物なしを提示。洗浄・縫合要否判断を促す。",
    "controllerChecklist": "特になし",
    "actingPoints": "傷の処置希望。\n【Walk-in・軽症】必須処置をしないまま帰宅を促された場合は、「症状が強くて帰られない」「必要な処置をしてください」と訴え、必須処置が終わるまで帰宅しないことをアピールする。",
    "focus": "軽症切創、止血確認、異物確認、縫合判断",
    "learningPoints": "",
    "branchConditions": "【必須処置】\n時間制限なし。以下を完了\n・創部処置\n【対応できた場合】\n必須処置を完了し、症状が軽減して帰宅\n【一つでも対応できなかった場合】\n症状が強く残り、患者が「なんとかしてください」と訴える",
    "postErSetting": "",
    "moulage": "",
    "originalId": "46",
    "originalCase": "[\"https://app.notion.com/7bc1502235fc4fa7a7c5eae75b5dc97c\"]"
  },
  {
    "id": 8,
    "notionPageId": "cc96b32c-2c70-46a4-8f7b-1ef81bbfb6cd",
    "name": "軽症頸部痛",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:15",
    "method": "徒歩",
    "expectedTriage": "緑",
    "clinicalZones": "[\"軽症\"]",
    "destination": "[\"帰宅\"]",
    "opeAg": "",
    "overview": "追突または地震後の軽い頚部痛として投入。軽い頚部痛。神経症状なし。",
    "chiefComplaint": "頸部痛",
    "rescueVitals": "",
    "primaryTriageFindings": "Walk-in。歩行: 可能。呼吸・脈拍・意識: すべて見たまま安定、指示に従える",
    "initialVitals": "実測値で安定",
    "exam": "神経脱落なし、正中圧痛なし。",
    "tests": "画像不要または異常なし。",
    "bloodGas": "",
    "specimenTests": "",
    "imaging": "",
    "treatment": "鎮痛/帰宅",
    "additionalEvent": "軽症者の説明・帰宅導線を確認。",
    "controllerInstruction": "神経症状なし、正中圧痛なしを提示。過剰検査を避けた帰宅判断を促す。",
    "controllerChecklist": "特になし",
    "actingPoints": "首が少し痛い程度。\n【Walk-in・軽症】必須処置をしないまま帰宅を促された場合は、「症状が強くて帰られない」「必要な処置をしてください」と訴え、必須処置が終わるまで帰宅しないことをアピールする。",
    "focus": "頚部痛評価、神経症状確認、帰宅判断",
    "learningPoints": "",
    "branchConditions": "【必須処置】\n時間制限なし。以下を完了\n・鎮痛\n【対応できた場合】\n必須処置を完了し、症状が軽減して帰宅\n【一つでも対応できなかった場合】\n症状が強く残り、患者が「なんとかしてください」と訴える",
    "postErSetting": "",
    "moulage": "",
    "originalId": "47",
    "originalCase": "[\"https://app.notion.com/4eda7c72483945dbaf02f9b938562a0c\"]"
  },
  {
    "id": 9,
    "notionPageId": "eb89641f-14ae-46fa-a3a0-e1c7735faae7",
    "name": "足関節捻挫",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:15",
    "method": "徒歩",
    "expectedTriage": "緑",
    "clinicalZones": "[\"軽症\"]",
    "destination": "[\"帰宅\"]",
    "opeAg": "",
    "overview": "避難中転倒による足関節捻挫として投入。軽度足関節捻挫。",
    "chiefComplaint": "足関節痛",
    "rescueVitals": "",
    "primaryTriageFindings": "Walk-in。歩行: 可能。呼吸・脈拍・意識: すべて見たまま安定、指示に従える",
    "initialVitals": "実測値で安定",
    "exam": "外踝周囲圧痛軽度。",
    "tests": "X線で骨折なし。",
    "bloodGas": "",
    "specimenTests": "",
    "imaging": "〇",
    "treatment": "固定/帰宅",
    "additionalEvent": "緑患者の同時多数来院として軽症ゾーン混雑を演出。",
    "controllerInstruction": "歩行可能、腫脹軽度、X線骨折なしを提示。固定・帰宅判断へ。",
    "controllerChecklist": "特になし",
    "actingPoints": "少し足を引きずる。\n【Walk-in・軽症】必須処置をしないまま帰宅を促された場合は、「症状が強くて帰られない」「必要な処置をしてください」と訴え、必須処置が終わるまで帰宅しないことをアピールする。",
    "focus": "捻挫、歩行可能評価、固定、帰宅判断",
    "learningPoints": "",
    "branchConditions": "【必須処置】\n時間制限なし。以下を完了\n・骨折部の固定\n・鎮痛\n【対応できた場合】\n必須処置を完了し、症状が軽減して帰宅\n【一つでも対応できなかった場合】\n症状が強く残り、患者が「なんとかしてください」と訴える",
    "postErSetting": "",
    "moulage": "",
    "originalId": "48",
    "originalCase": "[\"https://app.notion.com/82ce245d26a44bf4a295ab6a89bd53b1\"]"
  },
  {
    "id": 10,
    "notionPageId": "cbc545a2-61e5-45b8-b81d-abbb05db7bd8",
    "name": "手指切創",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:15",
    "method": "徒歩",
    "expectedTriage": "緑",
    "clinicalZones": "[\"軽症\"]",
    "destination": "[\"帰宅\"]",
    "opeAg": "",
    "overview": "ガラス片による手指小切創として投入。手指小切創、止血済み。",
    "chiefComplaint": "手指切創",
    "rescueVitals": "",
    "primaryTriageFindings": "Walk-in。歩行: 可能。呼吸・脈拍・意識: すべて見たまま安定、指示に従える",
    "initialVitals": "実測値で安定",
    "exam": "浅い切創、可動域良好。",
    "tests": "腱損傷なし。",
    "bloodGas": "",
    "specimenTests": "",
    "imaging": "",
    "treatment": "洗浄/テープ固定",
    "additionalEvent": "軽症創傷が複数同時に来る状況を作る。",
    "controllerInstruction": "止血済み、腱損傷なしを提示。洗浄・テープ固定で帰宅可能とする。",
    "controllerChecklist": "特になし",
    "actingPoints": "処置を待てる。\n【Walk-in・軽症】必須処置をしないまま帰宅を促された場合は、「症状が強くて帰られない」「必要な処置をしてください」と訴え、必須処置が終わるまで帰宅しないことをアピールする。",
    "focus": "手指切創、腱損傷確認、洗浄、帰宅導線",
    "learningPoints": "",
    "branchConditions": "【必須処置】\n時間制限なし。以下を完了\n・創部処置\n【対応できた場合】\n必須処置を完了し、症状が軽減して帰宅\n【一つでも対応できなかった場合】\n症状が強く残り、患者が「なんとかしてください」と訴える",
    "postErSetting": "",
    "moulage": "",
    "originalId": "49",
    "originalCase": "[\"https://app.notion.com/362ca852fb744c10bd8f408628e73713\"]"
  },
  {
    "id": 11,
    "notionPageId": "99681b3e-4b9a-4d4a-bd91-319967cb640d",
    "name": "頭痛・不眠",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:15",
    "method": "徒歩",
    "expectedTriage": "緑",
    "clinicalZones": "[\"軽症\"]",
    "destination": "[\"帰宅\"]",
    "opeAg": "",
    "overview": "災害ストレスによる頭痛・不眠としてWalk-in第1波に投入。避難ストレスによる頭痛と不眠。",
    "chiefComplaint": "頭痛・不眠",
    "rescueVitals": "",
    "primaryTriageFindings": "Walk-in。歩行: 可能。呼吸・脈拍・意識: すべて見たまま安定、指示に従える",
    "initialVitals": "実測値で安定",
    "exam": "神経脱落症状なし。",
    "tests": "検査不要。",
    "bloodGas": "",
    "specimenTests": "",
    "imaging": "",
    "treatment": "内服/帰宅",
    "additionalEvent": "軽症ゾーンで不安訴えへの対応を確認。",
    "controllerInstruction": "神経症状なし、バイタル安定を提示。傾聴と帰宅判断を促す。",
    "controllerChecklist": "特になし",
    "actingPoints": "疲労感と不眠を訴える。\n【Walk-in・軽症】必須処置をしないまま帰宅を促された場合は、「症状が強くて帰られない」「必要な処置をしてください」と訴え、必須処置が終わるまで帰宅しないことをアピールする。",
    "focus": "災害ストレス、過剰検査抑制、説明・帰宅判断",
    "learningPoints": "",
    "branchConditions": "【必須処置】\n時間制限なし。以下を完了\n・鎮痛\n【対応できた場合】\n必須処置を完了し、症状が軽減して帰宅\n【一つでも対応できなかった場合】\n症状が強く残り、患者が「なんとかしてください」と訴える",
    "postErSetting": "",
    "moulage": "",
    "originalId": "50",
    "originalCase": "[\"https://app.notion.com/b50d0bccdc094de89b170853127e5424\"]"
  },
  {
    "id": 12,
    "notionPageId": "2ac91d50-463e-4706-90a3-bbe2036ab23c",
    "name": "軽微外傷＋発熱（幼児）",
    "patientName": "ﾔﾏﾓﾄ ﾊﾙﾄ",
    "ageSex": "3歳/男児",
    "arrival": "10:15",
    "method": "徒歩",
    "expectedTriage": "緑",
    "clinicalZones": "[\"軽症\"]",
    "destination": "[\"帰宅\"]",
    "opeAg": "",
    "overview": "母同伴で徒歩来院した小児緑症例。軽症ゾーンで対応し帰宅／小児科引き継ぎ。もともと発熱のため小児科外来受診予定だったが、移動中に地震で転倒し受傷。外傷は軽微で、発熱・頻脈はあるが他バイタルは安定。緑判定とし、解熱対応のうえ帰宅または小児科へ引き継ぐ。",
    "chiefComplaint": "発熱",
    "rescueVitals": "",
    "primaryTriageFindings": "徒歩来院（母同伴）。歩行: 可能（幼児設定は保護者同伴で活気あり）。呼吸: RR 28、努力呼吸なし。循環: HR 150だが発熱性頻脈として扱い、末梢冷感なし。意識: 活気あり、指示/呼びかけに反応良好",
    "initialVitals": "BT 38.6、HR 150（発熱性頻脈）、SpO2 98%RA、RR 28、活気あり",
    "exam": "前額部・膝の擦過傷のみ、頭部血腫なし、咽頭発赤あり。神経学的異常なし。",
    "tests": "外傷検索の画像は基本不要。発熱に対し必要に応じ迅速検査。",
    "bloodGas": "",
    "specimenTests": "",
    "imaging": "",
    "treatment": "創処置＋解熱剤処方。発熱診療は小児科へ引き継ぎ／帰宅。",
    "additionalEvent": "母同伴で徒歩来院。発熱・頻脈があるが活気良好。小児科への引き継ぎ判断。",
    "controllerInstruction": "発熱性頻脈をショックと取り違えないよう指導。緑トリアージの妥当性を確認。",
    "controllerChecklist": "□ 発熱性頻脈をショックと取り違えず緑と判定\n□ 外傷は創処置のみで対応し画像の適応を判断\n□ 嘔吐・意識変容などの危険徴候を確認\n□ 発熱診療の行き先（小児科引き継ぎ／帰宅）を明確化\n□ 家族へ帰宅後のred flagを説明",
    "actingPoints": "乳幼児人形を使用。母役が付き添い「もともと発熱で小児科受診予定だった」と説明。外傷は軽微。\n\n【親（保護者）役：演技ポイント】\n- 子どもを抱っこ（または手をつなぐ）し、落ち着いた口調だが不安はある。\n- 最初に「もともと熱があって小児科に行く予定だった。地震で急いで出てくる時に転んで擦りむいた」と説明する。\n- 質問されたら：飲水はできている／尿は出ている／けいれんなし／嘔吐なし（危険徴候を否定できるように）。\n- 帰宅を促されたら：「熱があってつらそうで、まだ帰れないです。必要な処置と、小児科（または診察）につないでください」と訴える。\n- 方針が決まったら：帰宅なら「家で気をつけるサインを教えてください」／小児科へ引き継ぎなら「このまま小児科でみてもらえるんですね」と確認。\n\n【Walk-in・軽症】必須処置をしないまま帰宅を促された場合は、「症状が強くて帰られない」「必要な処置をしてください」と訴え、必須処置が終わるまで帰宅しないことをアピールする。",
    "focus": "小児の発熱＋軽微外傷、緑判定、小児科引き継ぎ／帰宅",
    "learningPoints": "幼児の発熱性頻脈（BT 38.6でHR 150）は生理的範囲であり、活気と末梢循環でショックと鑑別する。\n小児頭部外傷はPECARNルールで不要なCTを避ける。\n緑症例でも行き先（disposition）と原疾患のフォローを明確にする。",
    "branchConditions": "【必須処置】\n時間制限なし。以下を完了\n・創部処置\n・小児科\n【対応できた場合】\n必須処置を完了し、症状が軽減して小児科へ引き継ぎまたは帰宅\n【一つでも対応できなかった場合】\n症状が強く残り、患者が「なんとかしてください」と訴える",
    "postErSetting": "",
    "moulage": "",
    "originalId": "116",
    "originalCase": "[\"https://app.notion.com/70f8192a163943ccbf59f19360927bae\"]"
  },
  {
    "id": 13,
    "notionPageId": "d2653271-f7a9-48b3-8fb5-4d6ce5b5a156",
    "name": "重症頭部外傷（急性硬膜下血腫）",
    "patientName": "身元不明（ID未確認）",
    "ageSex": "13歳前後/男子（推定・中学生）",
    "arrival": "10:23",
    "method": "救急車",
    "expectedTriage": "赤",
    "clinicalZones": "[\"救外\"]",
    "destination": "[\"ICU\"]",
    "opeAg": "[\"OPE\"]",
    "overview": "張碓の多重事故で搬入された身元不明の小児赤症例。救急車で救外へ直行。張碓付近の多重事故に巻き込まれた身元不明の中学生。重症頭部外傷（急性硬膜下血腫）に加え、頭部の大きな裂創からの活動性出血により出血性ショックを呈す。気道確保・頭皮止血・輸血で循環は安定し、初期CTでは血腫は少量で緊急手術の適応なくICU入室となるが、ICU入室後に瞳孔不同が出現し血腫増大で緊急開頭術となる。",
    "chiefComplaint": "頭部外傷・頭皮出血",
    "rescueVitals": "BP 90/60（来院時、。頭部裂創・皮下血腫、呼びかけにうめくのみ、末梢冷感を伴う外傷性ショック。",
    "primaryTriageFindings": "歩行不能、呼びかけにうめき声のみ、頭皮裂創からの出血を伴うショックバイタル",
    "initialVitals": "BP 90/60（来院時、。頭部裂創・皮下血腫、呼びかけにうめくのみ、末梢冷感を伴う外傷性ショック",
    "exam": "来院時は瞳孔左右差・明らかな四肢麻痺なし。",
    "tests": "頭部CTで少量の急性硬膜下血腫。正中偏位・脳浮腫はなし。FASTは陰性。",
    "bloodGas": "〇",
    "specimenTests": "〇",
    "imaging": "〇",
    "treatment": "気管挿管（RSI）、頭皮止血・輸血。初期CTでは緊急手術の適応なく、挿管管理のままICU入室を調整する。",
    "additionalEvent": "気道確保（RSI）と頭皮止血・輸血を同時進行する。止血・輸血後にバイタルは安定し、初期CTでは緊急手術の適応なくICU入室を調整する。",
    "controllerInstruction": "初期CTは少量の急性硬膜下血腫で正中偏位・脳浮腫なし、FAST陰性と提示し、脳神経外科は緊急手術不要と判断させる。頭皮止血・輸血後はバイタル安定を伝え、挿管管理のままICU入室を調整させる。",
    "controllerChecklist": "□ GCS 8で頸椎保護下のRSIによる気管挿管を実施\n□ 頭皮裂創を圧迫・縫合／ステープルで止血\n□ 輸血を開始し、他部位の出血源をFASTなどで検索\n□ 初期CTの所見を脳神経外科と共有し方針を確認\n□ 挿管管理のままICU入室を調整\n□ 身元不明患者としての登録・緊急輸血・家族探索を並行",
    "actingPoints": "中学生役は学生が演じる（学生演技）。身元不明。来院時は呼びかけにうめくのみで反応が乏しい。救外退室時に学生演技を終了する。",
    "focus": "小児の頭皮出血によるショック、気道確保、ICU入室調整、身元不明対応",
    "learningPoints": "小児は頭皮出血だけでも出血性ショックに至るため、同時に他部位の出血源も検索する。\n低酸素・低血圧を避けることが二次性脳損傷予防の鍵で、GCS≤8は気道確保の適応。\n初期CTが軽微でも急性硬膜下血腫は増大しうるため、厳密な神経学的監視が必要。\n身元不明患者では、推定体重での薬剤投与・緊急輸血・家族探索を並行する。",
    "branchConditions": "【必須処置】\n初療開始から15分以内に必要な対応を選択\n・モニター装着\n・酸素投与\n・気道確保・挿管\n・末梢ルート確保\n・輸血\n・頭部挙上\n・脳神経外科\n・放射線科\n・ICU\n【対応できた場合】\n血圧120/70を維持し、挿管管理のままICUへ搬送\n【一つでも対応できなかった場合】\n低酸素・出血性ショックが進行し、二次性脳損傷へ悪化",
    "postErSetting": "ICU入室後、瞳孔不同が出現する。頭部CT再検で急性硬膜下血腫の増大を確認し、ICUから手術室へ搬送して緊急開頭血腫除去術を行う。術後はICU管理を継続する。",
    "moulage": "",
    "originalId": "115",
    "originalCase": "[\"https://app.notion.com/b8a3796c27d5428db87753be7d414506\"]"
  },
  {
    "id": 14,
    "notionPageId": "965bb492-782f-40f9-aecc-e8c27308961a",
    "name": "左腎損傷",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:25",
    "method": "乗用車",
    "expectedTriage": "緑",
    "clinicalZones": "[\"救外\"]",
    "destination": "[\"EU\"]",
    "opeAg": "[\"AG\"]",
    "overview": "乗用車2で来院。一見歩行可能だが二次トリアージ中に意識消失し、緑から赤へ変更する。張碓付近の多重衝突事故で背部を車内構造物にぶつけ左背部痛。一次では歩行可能だが、二次直前に座位で意識消失。臥位で改善するがショック状態。左腎損傷と造影剤血管外漏出を認め、TAE後にEU入院。",
    "chiefComplaint": "左背部痛",
    "rescueVitals": "",
    "primaryTriageFindings": "よろよろするが歩行可能  　RR28　脈拍100　CRT延長なし　従命可能",
    "initialVitals": "BP 76/30、HR 132、SpO2 96%RA。臥位では意識清明",
    "exam": "左背部の強い圧痛。顔面蒼白、冷汗。腹部は平坦・軟で腹膜刺激症状なし。",
    "tests": "FAST陰性。造影CT: 左腎損傷、造影剤血管外漏出あり。",
    "bloodGas": "〇",
    "specimenTests": "〇",
    "imaging": "〇",
    "treatment": "輸液・輸血、造影剤血管外漏出に対するTAE（AG）。",
    "additionalEvent": "乗用車2で来院。同乗者から「車内に動けない人がいる」と情報提供させる。",
    "controllerInstruction": "乗用車2。一次では軽症として振る舞わせ、二次直前に低血圧・意識消失を付与。救外移動を促す。",
    "controllerChecklist": "□ 一次では軽症として振る舞わせ、緑判定を許容する\n□ 二次トリアージ中に意識消失（２分くらいで外なら目を覚ます）、BP 76/30・HR 132・冷汗を提示する\n□ 赤へのトリアージアップと救外への移動が行われるか確認する\n□ FAST陰性、造影CTで左腎損傷＋造影剤血管外漏出を提示する\n□ 輸液・輸血を開始し、AG室へTAEを依頼して搬送を調整する",
    "actingPoints": "一次までは軽い左背部痛。二次トリアージ中に意識消失１－２分くらい。臥位で意識回復後、左背部痛を強く訴える。",
    "focus": "二次トリアージ、軽症に見える赤候補、腎損傷、ゾーン間移動",
    "learningPoints": "・受傷直後は代償により歩行可能でも、進行性出血で遅れてショック化する（トリアージアップの典型例）。\n・座位・起立での失神は循環血液量減少のサインであり、二次トリアージでの再評価が必要。\n・腎損傷ではFAST陰性でも造影CTで造影剤血管外漏出を確認し、TAEで止血する。",
    "branchConditions": "【必須処置】\n初療開始から15分以内に必要な対応を選択\n・モニター装着\n・末梢ルート確保\n・急速輸液\n・輸血\n・放射線科\n【対応できた場合】\n血圧100/60台・脈拍100前後に改善し、放射線科へ搬送\n【一つでも対応できなかった場合】\n血圧60台・脈拍140、意識低下・冷汗増強へ悪化",
    "postErSetting": "AG室でTAE後、循環は安定し、EU入院とする。",
    "moulage": "",
    "originalId": "108",
    "originalCase": "[\"https://app.notion.com/419cb18905a9431ca413137161cdc765\"]"
  },
  {
    "id": 15,
    "notionPageId": "6660d5d5-71f5-4fad-b729-3f1320e94c50",
    "name": "軽症胸部打撲",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:25",
    "method": "徒歩",
    "expectedTriage": "緑",
    "clinicalZones": "[\"軽症\"]",
    "destination": "[\"帰宅\"]",
    "opeAg": "",
    "overview": "張碓事故後に自力歩行で来院した軽症胸部打撲。軽い胸部打撲、呼吸苦なし。",
    "chiefComplaint": "胸部痛",
    "rescueVitals": "",
    "primaryTriageFindings": "Walk-in。歩行: 可能。呼吸: 見たまま安定、SpO2良好。脈拍・意識: 見たまま安定、指示に従える",
    "initialVitals": "SpO2 98%RA、他安定",
    "exam": "軽い圧痛、呼吸音左右差なし。",
    "tests": "X線で骨折なし。",
    "bloodGas": "",
    "specimenTests": "",
    "imaging": "〇",
    "treatment": "鎮痛/帰宅",
    "additionalEvent": "症例14と同じ事故グループの軽症者として来院し、車内残存者の情報を補助させる。",
    "controllerInstruction": "呼吸苦なし、SpO2良好、呼吸音左右差なしを提示。胸部外傷の過小評価に注意させる。",
    "controllerChecklist": "□ 呼吸苦なし、SpO2 98%RA、呼吸音左右差なしを提示する\n□ 深呼吸時の胸痛のみで緑判定が妥当であることを確認する\n□ X線で骨折なしを提示し、鎮痛・帰宅の判断を確認する",
    "actingPoints": "深呼吸で少し痛がる。\n【Walk-in・軽症】必須処置をしないまま帰宅を促された場合は、「症状が強くて帰られない」「必要な処置をしてください」と訴え、必須処置が終わるまで帰宅しないことをアピールする。",
    "focus": "胸部打撲、呼吸音確認、緑帰宅判断",
    "learningPoints": "",
    "branchConditions": "【必須処置】\n時間制限なし。以下を完了\n・鎮痛\n【対応できた場合】\n必須処置を完了し、症状が軽減して帰宅\n【一つでも対応できなかった場合】\n症状が強く残り、患者が「なんとかしてください」と訴える",
    "postErSetting": "",
    "moulage": "",
    "originalId": "51",
    "originalCase": "[\"https://app.notion.com/0ddb244337fd4a8e810c511ffe5fa2db\"]"
  },
  {
    "id": 16,
    "notionPageId": "62891f06-6840-4f92-b2ca-d225e7e3e9a7",
    "name": "軽いめまい",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:25",
    "method": "徒歩",
    "expectedTriage": "緑",
    "clinicalZones": "[\"軽症\"]",
    "destination": "[\"帰宅\"]",
    "opeAg": "",
    "overview": "避難疲労・軽度脱水による軽いめまいとして投入。軽いめまい、脱水軽度。",
    "chiefComplaint": "めまい",
    "rescueVitals": "",
    "primaryTriageFindings": "Walk-in。歩行: 可能。呼吸・脈拍・意識: すべて見たまま安定、指示に従える",
    "initialVitals": "実測値で安定",
    "exam": "麻痺なし、構音障害なし。",
    "tests": "必要時血糖正常。",
    "bloodGas": "",
    "specimenTests": "",
    "imaging": "",
    "treatment": "休息/水分",
    "additionalEvent": "症例5（回転性めまい）との重症度比較に使う。",
    "controllerInstruction": "神経症状なし、座位で改善を提示。水分・休息で帰宅可能とする。",
    "controllerChecklist": "□ 麻痺・構音障害なし、座位で改善することを提示する\n□ 必要時の血糖測定が行われるか確認する\n□ 水分・休息後の帰宅判断を確認する",
    "actingPoints": "座ると楽になる。\n【Walk-in・軽症】必須処置をしないまま帰宅を促された場合は、「症状が強くて帰られない」「必要な処置をしてください」と訴え、必須処置が終わるまで帰宅しないことをアピールする。",
    "focus": "軽症めまい、脱水、神経症状確認、帰宅判断",
    "learningPoints": "",
    "branchConditions": "【必須処置】\n時間制限なし。以下を完了\n・モニター装着\n【対応できた場合】\n必須処置を完了し、症状が軽減して帰宅\n【一つでも対応できなかった場合】\n症状が強く残り、患者が「なんとかしてください」と訴える",
    "postErSetting": "",
    "moulage": "",
    "originalId": "53",
    "originalCase": "[\"https://app.notion.com/1cb5e7c3f88d4fa7b790fd7a5303688c\"]"
  },
  {
    "id": 17,
    "notionPageId": "62bddc5a-aefd-456b-a145-31956bf199cb",
    "name": "一過性動悸",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:25",
    "method": "乗用車",
    "expectedTriage": "緑",
    "clinicalZones": "[\"軽症\"]",
    "destination": "[\"帰宅\"]",
    "opeAg": "",
    "overview": "乗用車2の乗員。事故後不安で動悸を訴えるが軽快する。張碓付近の多重衝突事故でマイクロバス後方座席に乗車。明らかな外傷はないが、事故後に動悸が強くなる。経過中に症状軽快。",
    "chiefComplaint": "動悸",
    "rescueVitals": "",
    "primaryTriageFindings": "歩行: 可能。呼吸・脈拍・意識: すべて見たまま安定、指示に従える",
    "initialVitals": "実測値",
    "exam": "余裕で歩行可能。症状は消失し、早く帰りたいと訴える。",
    "tests": "異常なし",
    "bloodGas": "",
    "specimenTests": "",
    "imaging": "",
    "treatment": "不要",
    "additionalEvent": "乗用車2の同乗者として来院。「まだ車内に動けない人がいる」と伝え、トリアージポストから搬送班要請を促す。",
    "controllerInstruction": "乗用車2。一次では動悸を訴え、二次では軽快。車内残存者情報を本人から申告させる。",
    "controllerChecklist": "□ 一次では動悸を訴え、二次では症状軽快とする\n□ 「まだ車内に動けない人がいる」と本人から申告させる\n□ トリアージポストから搬送班要請が出るか確認する\n□ 検査異常なしを提示し、帰宅判断を確認する",
    "actingPoints": "車から降りたら、まだ車内に動けない人がいると伝える。一次トリアージまでは動悸を訴え、その後は症状軽快として普通にふるまう。",
    "focus": "同乗者情報、車内残存者対応、不安症状、帰宅判断",
    "learningPoints": "",
    "branchConditions": "【必須処置】\n時間制限なし。以下を完了\n・モニター装着\n【対応できた場合】\n動悸が軽快し、バイタル安定。残存者情報を共有して帰宅\n【一つでも対応できなかった場合】\n動悸・バイタル異常の再評価、または車内残存者の搬送要請が遅延",
    "postErSetting": "",
    "moulage": "",
    "originalId": "91",
    "originalCase": "[\"https://app.notion.com/8360e61477614d54bd5f16897fe360dd\"]"
  },
  {
    "id": 18,
    "notionPageId": "e8fe78e4-e672-4ea5-a1ba-7c507e789744",
    "name": "左膝打撲",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:25",
    "method": "乗用車",
    "expectedTriage": "緑",
    "clinicalZones": "[\"軽症\"]",
    "destination": "[\"帰宅\"]",
    "opeAg": "",
    "overview": "乗用車2の乗員。マイクロバス乗車中に前座席へ左膝をぶつけた軽症外傷。マイクロバス乗車中、追突の衝撃で前の座席に左膝をぶつけた。歩行可能だが荷重時痛あり。",
    "chiefComplaint": "左膝痛",
    "rescueVitals": "",
    "primaryTriageFindings": "歩行: 可能（びっこを引くが自力歩行可）。呼吸・脈拍・意識: すべて見たまま安定、指示に従える",
    "initialVitals": "実測値",
    "exam": "左膝関節前面に圧痛、軽度腫脹。可動域制限は軽度。靭帯損傷を示唆する所見なし。",
    "tests": "画像異常なし",
    "bloodGas": "",
    "specimenTests": "",
    "imaging": "〇",
    "treatment": "不要",
    "additionalEvent": "乗用車2の軽症者として、同乗の症例14の急変と対比する。",
    "controllerInstruction": "乗用車2。びっこを引くが歩行可能。画像異常なしを提示し帰宅へ。",
    "controllerChecklist": "□ びっこを引くが自力歩行可能であることを提示する\n□ 靭帯不安定性を示す所見はないと提示する\n□ 画像異常なしを提示し、緑判定と帰宅の判断を確認する",
    "actingPoints": "びっこを引きながら歩行し、膝の曲げ伸ばしで疼痛を訴える。マイクロバス内で前座席に膝をぶつけたと説明する。",
    "focus": "膝打撲、歩行可能評価、軽症帰宅判断",
    "learningPoints": "",
    "branchConditions": "【必須処置】\n時間制限なし。以下を完了\n・鎮痛\n【対応できた場合】\n自力歩行可能・靭帯不安定性なく、帰宅\n【一つでも対応できなかった場合】\n歩行不能・腫脹増悪・不安定性が出現し、再評価が必要",
    "postErSetting": "",
    "moulage": "",
    "originalId": "92",
    "originalCase": "[\"https://app.notion.com/c7113ce143cc417b8df34f87cace151d\"]"
  },
  {
    "id": 19,
    "notionPageId": "0d9412c3-3629-4d3f-bfd4-ae099aceea25",
    "name": "右大腿骨骨折",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:32",
    "method": "救急車",
    "expectedTriage": "黄",
    "clinicalZones": "[\"救外\",\"軽症\"]",
    "destination": "[\"EU\",\"ICU\"]",
    "opeAg": "[\"OPE\"]",
    "overview": "救急車第2波と同時に搬入される歩行不能の黄症例。プレイヤー判断により、軽症ゾーン・救外ゾーンどちらもあり得る。コントローラーは両方を許容し、赤症例との優先順位差を確認する。転倒後の右大腿痛、歩行不能。循環安定。",
    "chiefComplaint": "右大腿部痛・歩行不能",
    "rescueVitals": "実測値で安定。",
    "primaryTriageFindings": "歩行不能、右大腿強い疼痛",
    "initialVitals": "実測値で安定",
    "exam": "右大腿圧痛、変形疑い。",
    "tests": "X線で右大腿骨骨折。",
    "bloodGas": "〇",
    "specimenTests": "〇",
    "imaging": "〇",
    "treatment": "鎮痛・下肢固定のうえ、骨接合術（OPE）。",
    "additionalEvent": "救急車④で搬入し、救外・軽症ゾーンの振り分けを確認。",
    "controllerInstruction": "右大腿痛と歩行不能を提示。循環安定を強調する。トリアージ黄色だが、軽症ゾーンで評価する判断・救外ゾーンで評価する判断のどちらも許容し、赤症例との優先順位差を確認させる。",
    "controllerChecklist": "□ 右大腿痛と歩行不能を提示し、循環は安定していることを強調する\n□ 救外ゾーン・軽症ゾーンのどちらの判断も許容する\n□ 赤症例との優先順位の付け方を確認する\n□ X線で右大腿骨骨折を提示し、鎮痛・下肢固定が行われるか確認する\n□ 骨接合術の手術室調整を確認する",
    "actingPoints": "右大腿を強く痛がる。麻痺なし。",
    "focus": "歩行不能、整形外傷、入院判断、赤症例との優先順位付け",
    "learningPoints": "・大腿骨骨折は多量出血をきたし得るため、循環の反復評価が必要。\n・早期の鎮痛と下肢固定が出血・疼痛コントロールに有用。\n・黄症例のゾーン配置は運用次第で、赤症例との優先順位付けが要点。",
    "branchConditions": "【必須処置】\n時間制限なし。以下を完了\n・モニター装着\n・鎮痛\n・骨折部の固定\n・整形外科\n・手術室/麻酔科\n【対応できた場合】\n疼痛・バイタルが安定し、手術待機へ\n【一つでも対応できなかった場合】\n大腿部腫脹・疼痛が増強し、頻脈・血圧低下へ悪化",
    "postErSetting": "骨接合術後はEUまたは一般病床へ入院する。",
    "moulage": "",
    "originalId": "20",
    "originalCase": "[\"https://app.notion.com/d438742ed6a44030bf496be320332d06\"]"
  },
  {
    "id": 20,
    "notionPageId": "90b5efe8-dbcf-482d-83b4-1df5cb70ab30",
    "name": "喘息発作",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:35",
    "method": "徒歩",
    "expectedTriage": "黄",
    "clinicalZones": "[\"軽症\"]",
    "destination": "[\"帰宅\"]",
    "opeAg": "",
    "overview": "建物粉塵吸入後の呼吸苦としてWalk-in第2波に投入。軽症ゾーンで呼吸状態を評価。喘鳴と呼吸苦。吸入で改善。",
    "chiefComplaint": "喘鳴・呼吸困難",
    "rescueVitals": "",
    "primaryTriageFindings": "Walk-in。歩行: 支え歩き。呼吸: RR 30、喘鳴あり（コントローラーが呼吸数30/分を提示）。循環: 脈拍数105、血圧は見たまま安定。意識: 指示に従える",
    "initialVitals": "SpO2 94%、RR 30、HR 105、BP安定",
    "exam": "喘鳴、軽度努力呼吸。会話は短文で可能。",
    "tests": "心電図変化なし。",
    "bloodGas": "",
    "specimenTests": "",
    "imaging": "",
    "treatment": "吸入/帰宅",
    "additionalEvent": "軽症ゾーン混雑時に呼吸器症状を混ぜ、黄判断を促す。",
    "controllerInstruction": "喘鳴、RR 30、SpO2 94%を提示。吸入後改善する想定を伝える。",
    "controllerChecklist": "□ 喘鳴、RR 30、SpO2 94%、HR 105を提示する\n□ 黄として軽症ゾーンで呼吸を優先評価する流れを確認する\n□ 吸入後にSpO2 97%、RR 20へ改善すると提示する\n□ 帰宅判断と増悪時の再診説明を確認する",
    "actingPoints": "短文で会話可能。咳込みあり、吸入後に改善。\n【Walk-in・軽症】必須処置をしないまま帰宅を促された場合は、「症状が強くて帰られない」「必要な処置をしてください」と訴え、必須処置が終わるまで帰宅しないことをアピールする。",
    "focus": "呼吸苦、吸入処置、酸素化確認、軽症ゾーンでの黄管理",
    "learningPoints": "",
    "branchConditions": "【必須処置】\n時間制限なし。以下を完了\n・モニター装着\n・酸素投与\n【対応できた場合】\n必須処置を完了し、症状が軽減して帰宅\n【一つでも対応できなかった場合】\n症状が強く残り、患者が「なんとかしてください」と訴える",
    "postErSetting": "",
    "moulage": "",
    "originalId": "23",
    "originalCase": "[\"https://app.notion.com/dd63e8eb16f949d4a1d01681eab5fa5e\"]"
  },
  {
    "id": 21,
    "notionPageId": "1f40bdb8-df35-407f-a299-b918ad3edca5",
    "name": "腰椎圧迫骨折",
    "patientName": "フリー",
    "ageSex": "高齢/フリー",
    "arrival": "10:35",
    "method": "乗用車",
    "expectedTriage": "黄",
    "clinicalZones": "[\"救外\"]",
    "destination": "[\"EU\",\"ICU\"]",
    "opeAg": "",
    "overview": "乗用車3で来院。地震後の自宅内転倒として来院。高齢設定は必要に応じてコントローラー説明で代替。転倒後腰痛で体動困難。",
    "chiefComplaint": "腰痛・体動困難",
    "rescueVitals": "",
    "primaryTriageFindings": "歩行: 歩行不能。呼吸: 見たまま安定。循環: 脈拍は見たまま、ショック所見なし。意識: 指示に従える",
    "initialVitals": "実測値で安定",
    "exam": "腰部正中叩打痛。",
    "tests": "CTで腰椎圧迫骨折。",
    "bloodGas": "〇",
    "specimenTests": "〇",
    "imaging": "〇",
    "treatment": "鎮痛・安静、体幹装具。",
    "additionalEvent": "乗用車3で来院。歩行不能患者が増え、車椅子・ストレッチャー不足を演出する。",
    "controllerInstruction": "体動困難、腰部叩打痛、神経症状なしを提示。画像検査・入院判断を促す。",
    "controllerChecklist": "□ 体動困難・腰部正中叩打痛・神経症状なしを提示する\n□ 車椅子・ストレッチャーなど移動手段の確保調整を確認する\n□ CTで腰椎圧迫骨折を提示する\n□ 鎮痛・安静・体幹装具とEU入院の調整を確認する",
    "actingPoints": "動かすと激痛、安静なら軽快。",
    "focus": "自宅内転倒、歩行不能、画像検査、入院判断",
    "learningPoints": "・高齢者の転倒後腰痛では圧迫骨折を想起し、麻痺・膀胱直腸障害の有無を確認する。\n・歩行不能例は入院適応となり、災害時は移動・搜送資源の確保も課題となる。",
    "branchConditions": "【必須処置】\n初療開始から15分以内に必要な対応を選択\n・鎮痛\n・骨折部の固定\n・整形外科\n【対応できた場合】\n疼痛が軽減し、神経症状なく入院調整へ\n【一つでも対応できなかった場合】\n下肢しびれ・尿閉・疼痛増悪が出現し、再評価が必要",
    "postErSetting": "EUまたは一般病床へ入院し、鎮痛・安静・体幹装具で管理する。",
    "moulage": "",
    "originalId": "24",
    "originalCase": "[\"https://app.notion.com/f9dfe8c8e58b46a2aa6b77f23a822936\"]"
  },
  {
    "id": 22,
    "notionPageId": "3c35095c-9da6-4c2d-8e51-7a7a9222bbd8",
    "name": "左多発肋骨骨折・小気胸",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:35",
    "method": "徒歩",
    "expectedTriage": "緑",
    "clinicalZones": "[\"救外\"]",
    "destination": "[\"EU\"]",
    "opeAg": "",
    "overview": "張碓事故後に自力来院した胸部外傷。歩行可能だが胸部外傷として黄扱い。左胸部痛。多発肋骨骨折と小気胸。",
    "chiefComplaint": "左胸部痛",
    "rescueVitals": "",
    "primaryTriageFindings": "Walk-in。歩行: 可能。呼吸: 呼吸数は見たまま、SpO2 96%RA、呼吸音やや低下。循環: 脈拍は見たまま安定。意識: 指示に従える",
    "initialVitals": "SpO2 96%RA、他安定",
    "exam": "左側胸部圧痛。",
    "tests": "X線/CTで多発肋骨骨折、小気胸。",
    "bloodGas": "〇",
    "specimenTests": "〇",
    "imaging": "〇",
    "treatment": "鎮痛・呼吸状態の反復評価。",
    "additionalEvent": "緑に見える胸部外傷を混ぜ、過小評価を防ぐ訓練にする。",
    "controllerInstruction": "SpO2は保たれるが胸痛が強い設定。画像で小気胸を提示し、EU入院の調整を促す。",
    "controllerChecklist": "□ 歩行可能でもSpO2 96%RA・呼吸音やや低下・強い胸痛を提示する\n□ 二次評価で黄へアップする判断を確認する\n□ X線／CTで多発肋骨骨折と小気胸を提示する\n□ 鎮痛と呼吸状態の反復評価が行われるか確認する\n□ EU入院の病床調整を行ったか",
    "actingPoints": "深呼吸で痛がる。呼吸苦は軽度。",
    "focus": "胸部外傷、小気胸、歩行可能でも黄判断、EU入院調整",
    "learningPoints": "・歩行可能でも胸部外傷は過小評価しない（二次評価でのトリアージアップ）。\n・小気胸は拡大リスクがあり、鎮痛と呼吸の反復評価のうえ入院観察が必要。\n・鎮痛不十分は無気肺・肺炎のリスクとなる。",
    "branchConditions": "【必須処置】\n初療開始から15分以内に必要な対応を選択\n・モニター装着\n・酸素投与\n・鎮痛\n【対応できた場合】\nSpO2 97%を維持し、深呼吸可能。EUへ搬送\n【一つでも対応できなかった場合】\n呼吸苦・SpO2低下・呼吸音低下が進行し、胸腔ドレーン留置を検討",
    "postErSetting": "EU入院後、鎮痛を継続し呼吸状態を観察する。SpO2 92%、RR 28、左呼吸音のさらなる低下を認めた場合は気胸拡大を疑い、胸腔ドレーンを検討する。",
    "moulage": "",
    "originalId": "25",
    "originalCase": "[\"https://app.notion.com/17f445f5db2d4c5fb4ea543fde655567\"]"
  },
  {
    "id": 23,
    "notionPageId": "1db904a7-f893-44e1-9f75-4349a04f70c9",
    "name": "安定型骨盤骨折",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:35",
    "method": "乗用車",
    "expectedTriage": "黄",
    "clinicalZones": "[\"救外\"]",
    "destination": "[\"EU\",\"ICU\"]",
    "opeAg": "",
    "overview": "乗用車3で来院。地震による自宅内転倒後の骨盤痛。循環安定の黄症例として入院評価。骨盤痛で歩行不能。循環安定。",
    "chiefComplaint": "骨盤部痛・歩行不能",
    "rescueVitals": "",
    "primaryTriageFindings": "歩行: 歩行不能。呼吸: 見たまま安定。循環: 脈拍は見たまま、ショック所見なし。意識: 指示に従える",
    "initialVitals": "実測値で安定",
    "exam": "骨盤圧痛、神経障害なし。",
    "tests": "CTで安定型骨盤骨折、漏出なし。",
    "bloodGas": "〇",
    "specimenTests": "〇",
    "imaging": "〇",
    "treatment": "鎮痛・安静。",
    "additionalEvent": "乗用車3で来院。赤の骨盤骨折（症例2）との重症度比較を行わせる。",
    "controllerInstruction": "過換気は徐々に改善。骨盤痛・歩行不能だがショックなしを提示。",
    "controllerChecklist": "□ 骨盤圧痛・歩行不能だがショック所見はないことを提示する\n□ 過換気は徐々に改善させる\n□ CTで安定型骨盤骨折、造影剤漏出なしを提示する\n□ 症例2（不安定型骨盤骨折）との重症度の違いを確認させる\n□ 鎮痛・安静とEU入院の調整を確認する",
    "actingPoints": "骨盤部疼痛、過換気は徐々に改善。",
    "focus": "骨盤骨折、循環安定、CT判断、赤黄の区別",
    "learningPoints": "・骨盤骨折は安定型と不安定型で循環動態と治療方針が大きく異なる。\n・ショック所見や造影剤漏出がなければTAEは不要で、鎮痛・安静と入院観察でよい。\n・過換気などの心因性反応をショックと取り違えない。",
    "branchConditions": "【必須処置】\n初療開始から15分以内に必要な対応を選択\n・モニター装着\n・鎮痛\n【対応できた場合】\n循環が安定し、鎮痛・安静のうえ入院調整へ\n【一つでも対応できなかった場合】\n脈拍110台・血圧90台へ変化し、再評価が必要",
    "postErSetting": "EUまたは一般病床へ入院し、鎮痛・安静で経過観察する。",
    "moulage": "",
    "originalId": "26",
    "originalCase": "[\"https://app.notion.com/b97080f682cc4cb88dfd6a1c27dc424e\"]"
  },
  {
    "id": 24,
    "notionPageId": "195cba97-e4f4-460b-9b03-1f4d5277d9df",
    "name": "頭部外傷・抗凝固薬内服",
    "patientName": "フリー",
    "ageSex": "高齢/フリー",
    "arrival": "10:35",
    "method": "徒歩",
    "expectedTriage": "緑",
    "clinicalZones": "[\"救外\"]",
    "destination": "[\"EU\"]",
    "opeAg": "",
    "overview": "自宅内転倒後の頭部外傷。抗凝固薬内服はコントローラー説明で補足する。転倒後の頭部外傷。抗凝固薬内服中で、前額部挫創と短期記憶障害を認める。頭部CTで少量の外傷性SAHを認め、EUで経過観察とする。",
    "chiefComplaint": "頭部外傷・物忘れ",
    "rescueVitals": "",
    "primaryTriageFindings": "Walk-in。歩行: 可能なら呼吸: 見たまま安定。循環: BP 113/74、HR 78。意識: 来院時JCS 1〜3程度、指示には従える",
    "initialVitals": "BP 113/74、HR 78、SpO2 98%、RR 18",
    "exam": "麻痺なし、瞳孔不同なし、短期記憶障害。",
    "tests": "頭部CTで外傷性SAH少量。",
    "bloodGas": "〇",
    "specimenTests": "〇",
    "imaging": "〇",
    "treatment": "抗凝固薬内服中の頭部外傷としてEU入院を調整する。",
    "additionalEvent": "高齢設定は人形または説明で代替し、学生には症状表現を中心に依頼。",
    "controllerInstruction": "同じ質問を繰り返す演技。頭部CTで少量外傷性SAHを提示し、観察判断を促す。",
    "controllerChecklist": "□ 同じ質問を繰り返す短期記憶障害を演じさせる\n□ 抗凝固薬内服と一時JCS20の病歴を二次評価で確認させる\n□ 一次緑から黄へアップし、救外へ移動する判断を確認する\n□ 頭部CTで少量の外傷性SAHを提示する\n□ EU入院を調整したか",
    "actingPoints": "同じ質問を繰り返す。",
    "focus": "頭部外傷、抗凝固薬、CT、経過観察、救外移動",
    "learningPoints": "・抗凝固薬内服例は軽微な頭部外傷でも遅発性の出血増大リスクが高い。\n・同じ質問の反復（短期記憶障害）は見逃されやすい意識障害のサイン。\n・少量のSAHでも遅発性増大リスクがあるため、反復評価が必要。",
    "branchConditions": "【必須処置】\n初療開始から15分以内に必要な対応を選択\n・モニター装着\n・頭部挙上\n・脳神経外科\n・放射線科\n【対応できた場合】\n意識JCS1〜3・バイタル安定で、EUへ搬送\n【一つでも対応できなかった場合】\n意識低下・頭痛・嘔吐が増悪し、再画像評価が必要",
    "postErSetting": "EU入院後、頭部CTを再検し、意識レベル・頭痛・嘔吐・瞳孔を反復評価する。JCS 20、頭痛・嘔吐増強、HR 55、BP 170/90が出現した場合は、CTで出血増大を確認して脳神経外科へ緊急コンサルトする。",
    "moulage": "",
    "originalId": "30",
    "originalCase": "[\"https://app.notion.com/5924039914184235b37c0b4a0cbe5193\"]"
  },
  {
    "id": 25,
    "notionPageId": "6d09940c-2745-461c-bf37-039a2b3fcde7",
    "name": "右肩脱臼",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:35",
    "method": "徒歩",
    "expectedTriage": "緑",
    "clinicalZones": "[\"軽症\"]",
    "destination": "[\"帰宅\"]",
    "opeAg": "",
    "overview": "転倒後の右肩痛としてWalk-in第2波に投入。処置が必要な黄症例。右肩脱臼疑い。疼痛強く挙上困難。",
    "chiefComplaint": "右肩痛・挙上困難",
    "rescueVitals": "",
    "primaryTriageFindings": "Walk-in。歩行: 可能。呼吸・脈拍・意識: すべて見たまま安定、指示に従える",
    "initialVitals": "実測値で安定",
    "exam": "右肩挙上不能、末梢循環保たれる。",
    "tests": "X線で右肩脱臼。",
    "bloodGas": "",
    "specimenTests": "",
    "imaging": "〇",
    "treatment": "整復/固定",
    "additionalEvent": "軽症ゾーンに処置待ち患者を増やし、処置優先順位を確認。",
    "controllerInstruction": "右肩変形と強い疼痛を提示。整復・固定の見なし処置を確認。",
    "controllerChecklist": "□ 右肩の変形・挙上不能・強い疼痛を提示する\n□ 末梢循環・知覚が保たれていることを提示する\n□ X線で右肩脱臼を提示する\n□ 鎮痛と整復・固定の見なし処置、軽症ゾーンでの処置優先順位を確認する",
    "actingPoints": "右肩を支えて痛がる。\n【Walk-in・軽症】整復・固定をしないまま帰宅を促された場合は、「肩が外れたままで痛くて帰られない。整復してください」と繰り返し訴え、整復・固定が終わるまで帰宅しないことをアピールする。",
    "focus": "脱臼、整復・固定、疼痛管理、軽症ゾーン処置",
    "learningPoints": "",
    "branchConditions": "【必須処置】\n時間制限なし。以下を完了\n・鎮痛\n・骨折部の固定\n・整形外科\n【対応できた場合】\n肩関節を整復、もしくは整形外科へコールし、症状が軽減して帰宅\n【一つでも対応できなかった場合】\n症状が強く残り、患者が「なんとかしてください」と訴える",
    "postErSetting": "",
    "moulage": "",
    "originalId": "31",
    "originalCase": "[\"https://app.notion.com/aa55e5b507564b208272b7dda898ac8f\"]"
  },
  {
    "id": 26,
    "notionPageId": "25632685-e0ff-4e41-a8d0-2c443c37b349",
    "name": "前腕骨折",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:35",
    "method": "乗用車",
    "expectedTriage": "緑",
    "clinicalZones": "[\"軽症\"]",
    "destination": "[\"帰宅\"]",
    "opeAg": "",
    "overview": "乗用車3で来院。地震時の転倒による上肢外傷として軽症ゾーンへ投入。前腕変形と疼痛。循環・感覚は保たれる。",
    "chiefComplaint": "前腕痛・変形",
    "rescueVitals": "",
    "primaryTriageFindings": "歩行: 可能。呼吸・脈拍・意識: すべて見たまま安定、指示に従える",
    "initialVitals": "実測値で安定",
    "exam": "末梢循環・知覚正常。",
    "tests": "X線で前腕骨折。",
    "bloodGas": "",
    "specimenTests": "",
    "imaging": "〇",
    "treatment": "整復/シーネ",
    "additionalEvent": "乗用車3で来院。処置待ちの黄症例を増やし、軽症ゾーンの優先順位を確認。",
    "controllerInstruction": "前腕変形・強い疼痛を提示し、末梢循環・感覚確認とシーネ固定を促す。",
    "controllerChecklist": "□ 前腕の変形・腫脹と強い疼痛を提示する\n□ 末梢循環・知覚が正常であることを提示する\n□ X線で前腕骨折を提示する\n□ 整復・シーネ固定と固定後の再評価を確認する",
    "actingPoints": "腕を動かすと強く痛がる。",
    "focus": "骨折評価、末梢循環確認、整復/シーネ固定",
    "learningPoints": "",
    "branchConditions": "【必須処置】\n時間制限なし。以下を完了\n・鎮痛\n・骨折部の固定\n・整形外科\n【対応できた場合】\n固定後に疼痛が軽減し、末梢循環・知覚を維持\n【一つでも対応できなかった場合】\n指のしびれ・冷感・腫脹増悪が出現し、緊急再評価が必要",
    "postErSetting": "",
    "moulage": "",
    "originalId": "32",
    "originalCase": "[\"https://app.notion.com/e492c686d2b74616acfe299354160f6a\"]"
  },
  {
    "id": 27,
    "notionPageId": "a16f5038-1ae0-4abf-ac38-e32fd6aaef87",
    "name": "粉塵吸入後の咳嗽",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:35",
    "method": "徒歩",
    "expectedTriage": "緑",
    "clinicalZones": "[\"軽症\"]",
    "destination": "[\"帰宅\"]",
    "opeAg": "",
    "overview": "建物損壊・粉塵曝露後の呼吸器症状として投入。粉塵曝露後の咳嗽と軽度低酸素。",
    "chiefComplaint": "咳嗽・呼吸苦",
    "rescueVitals": "",
    "primaryTriageFindings": "Walk-in。歩行: 可能。呼吸: RR 24、SpO2 93%RA、咳嗽あり。循環: 脈拍は見たまま安定。意識: 指示に従える",
    "initialVitals": "SpO2 93%RA、RR 24、他安定",
    "exam": "軽い喘鳴、呼吸苦軽度。",
    "tests": "胸部X線異常なし。",
    "bloodGas": "",
    "specimenTests": "",
    "imaging": "〇",
    "treatment": "酸素/吸入",
    "additionalEvent": "症例20（喘息発作）と合わせて呼吸器症状の鑑別・優先順位を確認。",
    "controllerInstruction": "すす汚れ、咳嗽、SpO2 93%を提示。酸素/吸入と経過観察を促す。",
    "controllerChecklist": "□すす汚れと咳嗽を提示する\n□一次は緑、二次評価でSpO2 93%RAを確認し黄へアップできるか\n□酸素・吸入の指示が出るか\n□胸部X線異常なしを提示する\n□再評価のうえ帰宅判断ができるか",
    "actingPoints": "咳き込みながら会話可能。\n【Walk-in・軽症】必須処置をしないまま帰宅を促された場合は、「症状が強くて帰られない」「必要な処置をしてください」と訴え、必須処置が終わるまで帰宅しないことをアピールする。",
    "focus": "粉塵吸入、軽度低酸素、吸入/酸素、黄判断",
    "learningPoints": "",
    "branchConditions": "【必須処置】\n時間制限なし。以下を完了\n・モニター装着\n・酸素投与\n【対応できた場合】\n必須処置を完了し、症状が軽減して帰宅\n【一つでも対応できなかった場合】\n症状が強く残り、患者が「なんとかしてください」と訴える",
    "postErSetting": "",
    "moulage": "",
    "originalId": "36",
    "originalCase": "[\"https://app.notion.com/2219551ada2a45028e8cb7799e04aaf1\"]"
  },
  {
    "id": 28,
    "notionPageId": "a495a622-0b8d-4c22-8bc4-22826b3f556c",
    "name": "低血糖",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:35",
    "method": "徒歩",
    "expectedTriage": "緑",
    "clinicalZones": "[\"軽症\"]",
    "destination": "[\"帰宅\"]",
    "opeAg": "",
    "overview": "避難中の食事不足による低血糖として軽症ゾーンへ投入。食事摂取不良による低血糖。",
    "chiefComplaint": "冷汗・ふらつき",
    "rescueVitals": "",
    "primaryTriageFindings": "Walk-in。歩行: 可能なら呼吸: 見たまま安定。循環: HR 100、冷汗あり。意識: 会話可能で指示に従える",
    "initialVitals": "HR 100、他安定",
    "exam": "冷汗、神経局在なし。",
    "tests": "血糖 48 mg/dL。",
    "bloodGas": "",
    "specimenTests": "",
    "imaging": "",
    "treatment": "ブドウ糖投与",
    "additionalEvent": "軽症に見える内因性疾患を混ぜ、血糖測定を促す。",
    "controllerInstruction": "冷汗・ふらつき・血糖48 mg/dLを提示。ブドウ糖投与後改善とする。",
    "controllerChecklist": "□冷汗・ふらつき・ぼんやりした様子を提示する\n□二次評価で血糖測定が行われるか\n□血糖48 mg/dLを提示する\n□ブドウ糖投与の指示が出るか\n□投与後の症状改善を確認し帰宅判断ができるか",
    "actingPoints": "ぼんやり、甘いもの摂取で改善。\n【Walk-in・軽症】必須処置をしないまま帰宅を促された場合は、「症状が強くて帰られない」「必要な処置をしてください」と訴え、必須処置が終わるまで帰宅しないことをアピールする。",
    "focus": "低血糖、意識変容予防、血糖測定、ブドウ糖投与",
    "learningPoints": "",
    "branchConditions": "【必須処置】\n時間制限なし。以下を完了\n・モニター装着\n・末梢ルート確保\n【対応できた場合】\n必須処置を完了し、症状が軽減して帰宅\n【一つでも対応できなかった場合】\n症状が強く残り、患者が「なんとかしてください」と訴える",
    "postErSetting": "",
    "moulage": "",
    "originalId": "37",
    "originalCase": "[\"https://app.notion.com/caac0165d62541c2b5e5bd6511c82a04\"]"
  },
  {
    "id": 29,
    "notionPageId": "638be1d5-a3d9-4eb5-8455-d0a9cc0b8158",
    "name": "不安・動悸",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:35",
    "method": "徒歩",
    "expectedTriage": "緑",
    "clinicalZones": "[\"軽症\"]",
    "destination": "[\"帰宅\"]",
    "opeAg": "",
    "overview": "災害ストレスによる不安・動悸としてWalk-in第2波に投入。災害ストレスによる不安と動悸。",
    "chiefComplaint": "不安・動悸",
    "rescueVitals": "",
    "primaryTriageFindings": "Walk-in。歩行: 可能。呼吸・脈拍・意識: すべて見たまま安定、指示に従える",
    "initialVitals": "実測値で安定",
    "exam": "胸部聴診異常なし。",
    "tests": "心電図異常なし。",
    "bloodGas": "",
    "specimenTests": "",
    "imaging": "",
    "treatment": "安静/説明",
    "additionalEvent": "軽症ゾーン混雑時に説明時間を要する患者を混ぜる。",
    "controllerInstruction": "不安は強いが会話可能、心電図異常なしを提示。安心説明と過剰検査抑制を促す。",
    "controllerChecklist": "□動悸・不安の訴えを繰り返す\n□バイタル安定・胸部聴診異常なしを提示する\n□心電図異常なしを提示する\n□傾聴と安心できる説明が行われるか\n□過剰検査を避けた帰宅判断ができるか",
    "actingPoints": "不安を繰り返し訴えるが会話可能。\n【Walk-in・軽症】必須処置をしないまま帰宅を促された場合は、「症状が強くて帰られない」「必要な処置をしてください」と訴え、必須処置が終わるまで帰宅しないことをアピールする。",
    "focus": "不安対応、動悸評価、家族/本人説明、過剰検査抑制",
    "learningPoints": "",
    "branchConditions": "【必須処置】\n時間制限なし。以下を完了\n・モニター装着\n【対応できた場合】\n必須処置を完了し、症状が軽減して帰宅\n【一つでも対応できなかった場合】\n症状が強く残り、患者が「なんとかしてください」と訴える",
    "postErSetting": "",
    "moulage": "",
    "originalId": "54",
    "originalCase": "[\"https://app.notion.com/44845eccf7e0421e8e4abb607887d927\"]"
  },
  {
    "id": 30,
    "notionPageId": "b53dc8be-3291-449e-880f-0d600a3683b6",
    "name": "膝擦過傷",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:35",
    "method": "徒歩",
    "expectedTriage": "緑",
    "clinicalZones": "[\"軽症\"]",
    "destination": "[\"帰宅\"]",
    "opeAg": "",
    "overview": "避難中転倒による膝擦過傷として投入。膝擦過傷、歩行可能。",
    "chiefComplaint": "膝擦過傷",
    "rescueVitals": "",
    "primaryTriageFindings": "Walk-in。歩行: 可能。呼吸・脈拍・意識: すべて見たまま安定、指示に従える",
    "initialVitals": "実測値で安定",
    "exam": "関節可動域良好。",
    "tests": "画像不要。",
    "bloodGas": "",
    "specimenTests": "",
    "imaging": "",
    "treatment": "洗浄/被覆",
    "additionalEvent": "軽症創傷の大量処理・帰宅導線確認に使用。",
    "controllerInstruction": "関節可動域良好、浅い擦過傷。洗浄・被覆後すぐ歩行可能とする。",
    "controllerChecklist": "特になし",
    "actingPoints": "処置後すぐ歩ける。\n【Walk-in・軽症】必須処置をしないまま帰宅を促された場合は、「症状が強くて帰られない」「必要な処置をしてください」と訴え、必須処置が終わるまで帰宅しないことをアピールする。",
    "focus": "擦過傷処置、関節評価、帰宅導線",
    "learningPoints": "",
    "branchConditions": "【必須処置】\n時間制限なし。以下を完了\n・創部処置\n【対応できた場合】\n必須処置を完了し、症状が軽減して帰宅\n【一つでも対応できなかった場合】\n症状が強く残り、患者が「なんとかしてください」と訴える",
    "postErSetting": "",
    "moulage": "",
    "originalId": "55",
    "originalCase": "[\"https://app.notion.com/c011a00dfd8b41faa568f0fe265f9b04\"]"
  },
  {
    "id": 31,
    "notionPageId": "9caa7d06-e412-465a-9e7b-fd32e20f6213",
    "name": "軽い腰痛",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:35",
    "method": "徒歩",
    "expectedTriage": "緑",
    "clinicalZones": "[\"軽症\"]",
    "destination": "[\"帰宅\"]",
    "opeAg": "",
    "overview": "自宅内転倒後の軽度腰痛として投入。軽度腰痛、神経症状なし。",
    "chiefComplaint": "軽い腰痛",
    "rescueVitals": "",
    "primaryTriageFindings": "Walk-in。歩行: 可能。呼吸・脈拍・意識: すべて見たまま安定、指示に従える",
    "initialVitals": "実測値で安定",
    "exam": "下肢麻痺なし、膀胱直腸障害なし。",
    "tests": "検査不要。",
    "bloodGas": "",
    "specimenTests": "",
    "imaging": "",
    "treatment": "鎮痛/帰宅",
    "additionalEvent": "症例21（腰椎圧迫骨折）との重症度比較に使う。",
    "controllerInstruction": "下肢麻痺なし、膀胱直腸障害なしを提示。赤旗確認後に帰宅判断へ。",
    "controllerChecklist": "特になし",
    "actingPoints": "腰を押さえるが歩ける。\n【Walk-in・軽症】必須処置をしないまま帰宅を促された場合は、「症状が強くて帰られない」「必要な処置をしてください」と訴え、必須処置が終わるまで帰宅しないことをアピールする。",
    "focus": "腰痛の赤旗確認、歩行可能評価、帰宅判断",
    "learningPoints": "",
    "branchConditions": "【必須処置】\n時間制限なし。以下を完了\n・鎮痛\n【対応できた場合】\n必須処置を完了し、症状が軽減して帰宅\n【一つでも対応できなかった場合】\n症状が強く残り、患者が「なんとかしてください」と訴える",
    "postErSetting": "",
    "moulage": "",
    "originalId": "56",
    "originalCase": "[\"https://app.notion.com/cfc483bc8dd94131bad8eb52567e4500\"]"
  },
  {
    "id": 32,
    "notionPageId": "035ce1c6-e4b1-47b6-8291-fd2058ea886b",
    "name": "鼻出血",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:35",
    "method": "徒歩",
    "expectedTriage": "緑",
    "clinicalZones": "[\"軽症\"]",
    "destination": "[\"帰宅\"]",
    "opeAg": "",
    "overview": "衝突時の顔面打撲による鼻出血として投入。鼻出血、圧迫で止血。",
    "chiefComplaint": "鼻出血",
    "rescueVitals": "",
    "primaryTriageFindings": "Walk-in。歩行: 可能。呼吸・脈拍・意識: すべて見たまま安定、指示に従える",
    "initialVitals": "実測値で安定",
    "exam": "顔面変形なし、止血確認。",
    "tests": "追加検査不要。",
    "bloodGas": "",
    "specimenTests": "",
    "imaging": "",
    "treatment": "圧迫止血",
    "additionalEvent": "軽症ゾーンで見た目に出血がある患者を混ぜる。",
    "controllerInstruction": "圧迫で止血可能、顔面変形なしを提示。止血確認と帰宅説明を促す。",
    "controllerChecklist": "□鼻を押さえて来院し、鼻出血少量・意識清明を提示する\n□正しい部位の圧迫止血が行われるか\n□顔面変形の有無を確認するか\n□止血確認と帰宅時の説明ができるか",
    "actingPoints": "鼻を押さえて来院。\n【Walk-in・軽症】必須処置をしないまま帰宅を促された場合は、「症状が強くて帰られない」「必要な処置をしてください」と訴え、必須処置が終わるまで帰宅しないことをアピールする。",
    "focus": "鼻出血対応、顔面外傷評価、止血確認",
    "learningPoints": "",
    "branchConditions": "【必須処置】\n時間制限なし。以下を完了\n・創部処置\n【対応できた場合】\n必須処置を完了し、症状が軽減して帰宅\n【一つでも対応できなかった場合】\n症状が強く残り、患者が「なんとかしてください」と訴える",
    "postErSetting": "",
    "moulage": "",
    "originalId": "58",
    "originalCase": "[\"https://app.notion.com/00bbce3eac0b42519a71b9f037a556e0\"]"
  },
  {
    "id": 33,
    "notionPageId": "13119f7c-f2c6-491f-ac68-7a9f5378297e",
    "name": "小児下腿骨折（閉鎖骨折）",
    "patientName": "ｺﾊﾞﾔｼ ﾐｵ",
    "ageSex": "7歳/女児",
    "arrival": "10:35",
    "method": "乗用車",
    "expectedTriage": "黄",
    "clinicalZones": "[\"軽症\"]",
    "destination": "[\"EU\",\"ICU\"]",
    "opeAg": "",
    "overview": "乗用車4で来院の小児黄症例。軽症ゾーン二次トリアージ→整形対応・入院。地震で倒れた塀に下腿を挟まれ受傷。開放創はなく下腿骨折。頻脈はあるが他バイタルは正常。鎮静下の徒手整復＋固定で対応する。",
    "chiefComplaint": "下腿痛",
    "rescueVitals": "",
    "primaryTriageFindings": "歩行: 歩行不能。呼吸: RR 24、努力呼吸なし。循環: HR 120、足背動脈触知良好、ショック所見なし。意識: 指示に従える",
    "initialVitals": "HR 120、BP 100/65、SpO2 99%RA、RR 24、BT 36.9",
    "exam": "下腿中央の変形・圧痛・腫脹、開放創なし、足背動脈触知良好、末梢神経障害なし。",
    "tests": "X線で脛骨・腓骨骨折。コンパートメント症候群に注意。",
    "bloodGas": "",
    "specimenTests": "",
    "imaging": "〇",
    "treatment": "鎮静下に徒手整復＋シーネ固定、整形外科コンサル。",
    "additionalEvent": "乗用車4で家族同伴来院。軽症ゾーンでの小児対応と鎮静下処置の準備を確認する。",
    "controllerInstruction": "末梢循環・神経所見の維持を確認。疼痛管理と鎮静下整復の準備を促す。",
    "controllerChecklist": "□足背動脈・感覚・足趾運動を評価するか\n□開放創の有無を確認するか\n□疼痛管理が早期に行われるか\n□鎮静下整復の準備とモニタリングができるか\n□固定前後で神経血管所見を再確認するか\n□整形外科コンサルと入院調整ができるか",
    "actingPoints": "学童人形を使用。倒れた塀に下腿を挟まれた設定。動かすと強く痛がるが末梢循環・感覚は保たれる。",
    "focus": "小児閉鎖骨折、末梢循環・神経評価、鎮静下整復",
    "learningPoints": "圧挫肢ではコンパートメント症候群の6P（疼痛・蒼白・脈拍消失・感覚異常・運動麻痺・緊満）を経時評価する。\n閉鎖骨折でも長時間圧迫があればクラッシュ症候群（再灌流による高K血症・横紋筋融解・AKI）を念頭に置く。\n小児の手技的鎮静は安全管理とモニタリングが必須。\n固定の前後で神経血管所見を繰り返し確認する。",
    "branchConditions": "【必須処置】\n時間制限なし。以下を完了\n・モニター装着\n・末梢ルート確保\n・鎮痛\n・骨折部の固定\n・整形外科\n・小児科\n【対応できた場合】\n末梢循環・知覚を維持し、整復・固定後に入院調整へ\n【一つでも対応できなかった場合】\n疼痛増強・腫脹緊満・感覚異常、または長時間圧迫による高K血症へ悪化",
    "postErSetting": "",
    "moulage": "",
    "originalId": "118",
    "originalCase": "[\"https://app.notion.com/98b5b6071b8e435fae3e4f20d7364235\"]"
  },
  {
    "id": 34,
    "notionPageId": "4eeb74d1-a8ca-403b-849e-7abebfb5a456",
    "name": "左手掌切創",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:40",
    "method": "乗用車",
    "expectedTriage": "緑",
    "clinicalZones": "[\"軽症\"]",
    "destination": "[\"帰宅\"]",
    "opeAg": "",
    "overview": "乗用車4で来院。被災したスーパーでのガラス・破片による左手掌切創。被災したスーパーで割れたガラスや飛散した破片で左手掌を負傷。左手掌切創、止血済み。縫合し帰宅。",
    "chiefComplaint": "左手掌切創",
    "rescueVitals": "",
    "primaryTriageFindings": "歩行: 可能。呼吸・脈拍・意識: すべて見たまま安定、指示に従える",
    "initialVitals": "実測値",
    "exam": "左手掌母指球部に約3cmの切創。深さは皮下組織まで。手指屈伸可能。",
    "tests": "異物なし。腱損傷・神経損傷なし。",
    "bloodGas": "",
    "specimenTests": "",
    "imaging": "",
    "treatment": "洗浄、縫合",
    "additionalEvent": "乗用車4で来院。ムラージュ対象として学生演技の視認性を高める。",
    "controllerInstruction": "止血済み、腱・神経損傷なしを提示。洗浄・縫合の見なし処置を促す。",
    "controllerChecklist": "□止血済みのガーゼ圧迫の状態を提示する\n□異物・腱損傷・神経損傷の評価が行われるか\n□手指の自動屈伸と知覚を確認するか\n□洗浄・縫合の見なし処置ができるか\n□帰宅説明ができるか",
    "actingPoints": "左手をガーゼで圧迫したまま来院。血が滲んでいることを心配し、傷口を見られると顔をそむける。",
    "focus": "切創処置、ムラージュ、縫合判断、帰宅導線",
    "learningPoints": "",
    "branchConditions": "【必須処置】\n時間制限なし。以下を完了\n・創部処置\n・外科\n【対応できた場合】\n止血・洗浄・縫合を行い、帰宅\n【一つでも対応できなかった場合】\n異物・腱損傷・神経損傷を見逃し、専門的処置が遅延",
    "postErSetting": "",
    "moulage": "",
    "originalId": "95",
    "originalCase": "[\"https://app.notion.com/1f1b7312b4294b55a843e191ef57a080\"]"
  },
  {
    "id": 35,
    "notionPageId": "130eeae1-695b-4741-b9a1-dbe58f59fb99",
    "name": "左外傷性血気胸・皮下気腫",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:42",
    "method": "救急車",
    "expectedTriage": "赤",
    "clinicalZones": "[\"救外\"]",
    "destination": "[\"EU\"]",
    "opeAg": "",
    "overview": "救急車第3波。呼吸不全を伴う胸部外傷として症例40（肝損傷）と同時搬入。張碓付近のマイクロバス多重衝突で転倒し胸部を強打。左前胸部痛、喀血、酸素化低下。左外傷性血気胸と皮下気腫。胸腔ドレナージ、挿管、人工呼吸器で安定化。人工呼吸管理はEUで継続する。",
    "chiefComplaint": "左胸部痛・呼吸困難",
    "rescueVitals": "JCS10、GCS 13（E3V4M6）、HR 130、BP 85/45、SpO2 90%（15Lリザーバー）",
    "primaryTriageFindings": "JCS10、左前胸部圧痛、喀血、左呼吸音減弱、頸静脈怒張",
    "initialVitals": "JCS10、GCS 13（E3V4M6）、HR 130、BP 85/45、SpO2 90%（15Lリザーバー）",
    "exam": "左前胸部圧痛、左呼吸音聴取せず、皮下気腫あり。",
    "tests": "胸部X線/CT: 左外傷性血気胸、皮下気腫。",
    "bloodGas": "〇",
    "specimenTests": "〇",
    "imaging": "〇",
    "treatment": "左胸腔ドレナージ、気管挿管・人工呼吸管理。",
    "additionalEvent": "重症呼吸管理症例が同時に増え、本部との病床調整を確認する。",
    "controllerInstruction": "胸腔ドレナージ後も酸素化不十分なら挿管・人工呼吸器管理を提示し、EU受け入れ病床の確保を促す。",
    "controllerChecklist": "□ 頸静脈怒張・左呼吸音消失・ショックを提示する\n□ 画像を待たずに胸腔減圧・胸腔ドレーンが行われるか\n□ 陽圧換気の前に胸腔が減圧されているか\n□ ドレナージ後も酸素化不十分なら挿管・人工呼吸管理へ移行できるか\n□ 人工呼吸管理を継続できる入院先を本部と調整したか",
    "actingPoints": "目を閉じ、呼びかけで開眼。左前胸部を押さえ、時々咳き込み口元を押さえる。挿管後は目を閉じる。",
    "focus": "血気胸、挿管、人工呼吸器、病床調整",
    "learningPoints": "緊張性気胸は臨床診断で即時減圧し、画像を待たない。\n陽圧換気の前に胸腔ドレーンを留置する。\n皮下気腫は気道・肺損傷を、頸静脈怒張は閉塞性ショックを示唆する。\n安定化後は人工呼吸管理を継続できる病床を早期に確保する。",
    "branchConditions": "【必須処置】\n初療開始から15分以内に必要な対応を選択\n・モニター装着\n・酸素投与\n・気道確保・挿管\n・胸腔ドレーン留置\n・心臓血管外科\n・ICU\n【対応できた場合】\n血圧・SpO2が改善し、入院先へ搬送\n【一つでも対応できなかった場合】\n緊張性気胸が増悪し、閉塞性ショック・心停止へ進行",
    "postErSetting": "EU入院後も気管挿管・人工呼吸管理を継続する。",
    "moulage": "",
    "originalId": "101",
    "originalCase": "[\"https://app.notion.com/1cd2dabbc3c44708909a989293e219df\"]"
  },
  {
    "id": 36,
    "notionPageId": "179222af-c840-4708-a1be-f2ed9abd5e1e",
    "name": "重症心身障害児の低酸素（酸素供給途絶）",
    "patientName": "ﾀﾅｶ ｿﾗ",
    "ageSex": "10歳/男児（重症心身障害児）",
    "arrival": "10:42",
    "method": "乗用車",
    "expectedTriage": "赤",
    "clinicalZones": "[\"救外\"]",
    "destination": "[\"ICU\"]",
    "opeAg": "",
    "overview": "乗用車5で家族同伴来院。停電による酸素供給途絶の低酸素。救外対応→入院。気管切開＋在宅人工呼吸器＋在宅酸素療法（HOT）管理の重症心身障害児。地震による停電で在宅の酸素濃縮器が停止し酸素供給が途絶。人工呼吸器は内蔵バッテリーで換気を継続したが、酸素化が得られずSpO2 80%台に低下して受診。小児重症例としてICUまたは小児科病棟での管理調整を依頼。",
    "chiefComplaint": "低酸素・呼吸困難",
    "rescueVitals": "",
    "primaryTriageFindings": "歩行: 歩行不能。呼吸: 用手換気下、SpO2 82%、努力呼吸あり。循環: HR 140、BPは正常範囲。意識: 反応はあるが重症心身障害児設定で評価困難",
    "initialVitals": "SpO2 82%（用手換気下）、HR 140、BP 正常範囲、RR 補助換気、BT 37.0",
    "exam": "気管切開部に問題なし、両肺で換気音聴取、痰貯留あり、酸素化不良。",
    "tests": "血液ガスで低酸素血症。胸部X線で無気肺/痰貯留を評価。",
    "bloodGas": "〇",
    "specimenTests": "〇",
    "imaging": "〇",
    "treatment": "酸素供給の確保・吸引・換気の安定化。小児科・ICUへ受け入れを依頼する。",
    "additionalEvent": "乗用車5で家族が用手換気しながら来院。母親は症例37として同時受付となる。",
    "controllerInstruction": "停電時のHOT/人工呼吸器の挙動（内蔵バッテリーは作動するが酸素供給は途絶）を解説。酸素源確保と入院調整を促す。",
    "controllerChecklist": "□ 停電で酸素濃縮器が停止した経緯を家族から聴取できるか\n□ まず換気ができているかを確認するか\n□ DOPE（逸脱・閉塞・気胸・機器不良）を系統的に評価するか\n□ 酸素源（配管・ボンベ）の確保と気管吸引ができるか\n□ 改善なければ気管切開チューブ交換へエスカレーションできるか\n□ 小児重症例として小児科・ICUへ受け入れを依頼したか",
    "actingPoints": "重症心身障害児の人形＋気管切開・人工呼吸器モデルを使用。家族役が「地震で停電し酸素濃縮器が止まった」と説明し、用手換気しながら搬入。",
    "focus": "在宅医療（HOT・在宅人工呼吸器）の停電トラブル、酸素供給確保、入院調整",
    "learningPoints": "HOTの酸素濃縮器は電力依存で、停電は酸素供給の停止に直結する。\n在宅人工呼吸器は内蔵バッテリーで換気を維持できても酸素化は低下しうる。\n気管切開・人工呼吸器トラブルはDOPEで系統的に評価し、吸引→チューブ交換へエスカレーションする。\n小児重症例としてICU・小児科と早期に連携する。",
    "branchConditions": "【必須処置】\n初療開始から15分以内に必要な対応を選択\n・モニター装着\n・酸素投与\n・気道確保・挿管\n・末梢ルート確保\n・小児科\n・ICU\n【対応できた場合】\n酸素再供給・換気が安定し、ICUへ搬送\n【一つでも対応できなかった場合】\n低酸素が遷延し、徐脈からCPAへ進行",
    "postErSetting": "ICU入室後も酸素供給・気管切開・人工呼吸管理を継続し、小児科と共同管理する。",
    "moulage": "",
    "originalId": "119",
    "originalCase": "[\"https://app.notion.com/2e844d3f75aa41d59a8c4724c8139ce0\"]"
  },
  {
    "id": 37,
    "notionPageId": "2260fe2a-714d-49ab-859b-cd3b6f021f4f",
    "name": "前額部擦過傷データベースを更新します。",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:48",
    "method": "乗用車",
    "expectedTriage": "緑",
    "clinicalZones": "[\"軽症\"]",
    "destination": "[\"帰宅\"]",
    "opeAg": "",
    "overview": "症例36の母親。乗用車5で症例36に付き添って来院し、自宅で受けた前額部の軽症外傷を訴える。地震の揺れで自宅内の家具に前額部をぶつけて受傷。擦過傷あり、ガーゼ圧迫で止血済み。縫合不要。症例36の母親で、付き添い来院の際に自身の傷も診てもらう。",
    "chiefComplaint": "前額部擦過傷",
    "rescueVitals": "",
    "primaryTriageFindings": "乗用車5（症例36の母親）。歩行: 可能。呼吸・脈拍・意識: すべて見たまま安定、指示に従える",
    "initialVitals": "実測値。頭痛・嘔気・意識障害なし",
    "exam": "前額部5×3cm大の擦過傷。表皮剥離、軽度滲出。",
    "tests": "異常なし",
    "bloodGas": "",
    "specimenTests": "",
    "imaging": "",
    "treatment": "洗浄、被覆、ステリテープ等",
    "additionalEvent": "乗用車5で症例36に付き添って来院。重症児対応と並行して家族の軽症外傷をどう処理するかを問う。",
    "controllerInstruction": "症例36の母親として来院。頭痛・嘔気・意識障害なし。洗浄・被覆・ステリテープで帰宅可能とする。症例36の対応状況を母親へ説明する場面も設定できる。",
    "controllerChecklist": "特になし",
    "actingPoints": "前額部の傷を気にして触ろうとする。痛みは軽度。\n\n【親（保護者）役：症例36の付き添い】\n地震で停電して酸素濃縮器が止まったことを説明し、子ども（症例36）を最優先にしてほしいと訴える。\n- 「地震で停電して、酸素濃縮器が止まりました」\n- 「呼吸器はバッテリーで動いていますが、酸素が出なくてSpO2が下がってきました」\n- 「今は用手換気（バッグ）で来ました」\n- 「私の傷は後でいいです。子どもを先にお願いします」\n\n質問されたら：\n- 気管切開あり／痰が多く吸引が必要な子\n- 低酸素は停電後から進行\n- 予備ボンベは残量が少ない（または途中で切れた）\n- 「まず酸素をください。吸引も必要かもしれません」\n\n方針が決まったら：\n- 「入院が必要ならお願いします。家は停電で戻れません」\n- 「電源と酸素が確保できる場所でお願いします」",
    "focus": "顔面擦過傷、頭部外傷除外、ムラージュ、家族対応、帰宅判断",
    "learningPoints": "",
    "branchConditions": "【必須処置】\n時間制限なし。以下を完了\n・創部処置\n【対応できた場合】\n前額部を処置し、帰宅\n【一つでも対応できなかった場合】\n頭痛・嘔気・意識障害を見逃し、頭部外傷の評価が遅延",
    "postErSetting": "",
    "moulage": "",
    "originalId": "100",
    "originalCase": "[\"https://app.notion.com/ebaee666fcdc4968b7c7224f47e77303\"]"
  },
  {
    "id": 38,
    "notionPageId": "da93e47e-0ae2-49ad-8159-206ee7cf84c3",
    "name": "脳梗塞疑い",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:50",
    "method": "乗用車",
    "expectedTriage": "黄",
    "clinicalZones": "[\"救外\"]",
    "destination": "[\"EU\",\"ICU\"]",
    "opeAg": "",
    "overview": "乗用車4に同乗して来院。スーパーで被災時に倒れ、外傷はないが体動困難となった。軽症ゾーンから救外へ移動すべき黄症例。近隣のスーパーで被災した際に倒れ、明らかな外傷はないがその後体動困難となり、乗用車4に同乗して来院。右上下肢脱力と構音障害を認め、発症からの時間経過あり。",
    "chiefComplaint": "右上下肢脱力・呂律不良",
    "rescueVitals": "",
    "primaryTriageFindings": "歩行: 不安定で自力歩行困難。呼吸: 見たまま安定。循環: 脈拍は見たまま安定。意識: 指示に従えるが呂律不良あり",
    "initialVitals": "実測値で安定",
    "exam": "バレー陽性、右上下肢軽度脱力。",
    "tests": "MRIで脳梗塞。",
    "bloodGas": "〇",
    "specimenTests": "〇",
    "imaging": "〇",
    "treatment": "脳卒中対応（画像評価・再灌流療法の適応判断）。",
    "additionalEvent": "乗用車4の同乗者として来院。軽症ゾーン混雑時に紛れ込ませ、再評価とゾーン間連絡を確認。",
    "controllerInstruction": "乗用車4。スーパーで倒れた後の体動困難として登場させ、右上下肢脱力と構音障害を提示。二次トリアージで救外移動を判断させる。",
    "controllerChecklist": "□右上下肢の脱力と呂律不良を提示する\n□二次トリアージで神経所見（バレー徴候・構音）を取り直すか\n□発症時刻／最終未発症時刻を確認するか\n□軽症ゾーンから救外へ移動し脳卒中コードを起動できるか\n□画像評価と再灌流療法の適応判断ができるか",
    "actingPoints": "右足が出しにくく、少し呂律が回らない。",
    "focus": "脳卒中疑い、二次トリアージ、救外移動、内因性疾患対応",
    "learningPoints": "脳梗塞は歩行可能でも緊急度が高く、片麻痺・構音障害はトリアージアップの根拠となる。\nrt-PA（発症4.5時間以内）や血栓回収療法の適応は発症時刻に依存するため、最終未発症時刻の確認が最重要。\n二次トリアージで神経所見を取り直す再評価が鍵となる。\n災害時でも内因性疾患は発生し、限られた画像・人的資源の中で適応を判断する。",
    "branchConditions": "【必須処置】\n初療開始から15分以内に必要な対応を選択\n・モニター装着\n・頭部挙上\n・脳神経外科\n・放射線科\n【対応できた場合】\n神経所見・発症時刻を確認し、画像評価・再灌流療法へ\n【一つでも対応できなかった場合】\n治療可能時間を逸失し、麻痺・梗塞が進行",
    "postErSetting": "再灌流療法の適応があればrt-PAまたは血栓回収療法へ進み、治療後はEUで神経所見を監視する。",
    "moulage": "",
    "originalId": "27",
    "originalCase": "[\"https://app.notion.com/3f6bff885d5b47a38189ab7da7883dbe\"]"
  },
  {
    "id": 39,
    "notionPageId": "5335fd6d-45f9-402f-a81f-65411805790b",
    "name": "急性腹症疑い",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:50",
    "method": "徒歩",
    "expectedTriage": "緑",
    "clinicalZones": "[\"救外\"]",
    "destination": "[\"EU\"]",
    "opeAg": "",
    "overview": "地震・事故とは別の体調不良が混在。腹痛強く、軽症ゾーンから救外評価へ。腹痛と嘔吐。脱水傾向あり。",
    "chiefComplaint": "腹痛・嘔吐",
    "rescueVitals": "",
    "primaryTriageFindings": "Walk-in。歩行: 可能。呼吸: 見たまま安定。循環: HR 105、脱水傾向あり。意識: 指示に従える",
    "initialVitals": "HR 105、他安定",
    "exam": "右下腹部圧痛、反跳痛なし。",
    "tests": "採血で脱水、CTで虫垂炎/腸炎鑑別。",
    "bloodGas": "〇",
    "specimenTests": "〇",
    "imaging": "〇",
    "treatment": "輸液・鎮痛・画像評価、外科コンサルト。",
    "additionalEvent": "軽症ゾーン混雑時に非外傷疾患を混ぜ、見落としを防ぐ訓練にする。",
    "controllerInstruction": "腹痛・嘔吐・脱水傾向を提示し、画像評価と救外移動の判断を促す。",
    "controllerChecklist": "□ 二次トリアージでHR105・嘔吐反復・脱水を確認したか\n□ 「歩けるから緑」で固定せず再評価したか\n□ 輸液・鎮痛を開始したか\n□ 画像（CT）の必要性と優先順位を判断したか\n□ 外科へコンサルトし、EU入院を調整したか",
    "actingPoints": "腹部を押さえてうずくまる。",
    "focus": "急性腹症、脱水、救外移動、画像判断",
    "learningPoints": "歩行可能な腹痛でも、頻脈（HR105）・反復する嘔吐・脱水は緊急度上昇のサイン。\n反跳痛がなくても虫垂炎・腸炎は経時的に進行するため、一度のトリアージで固定せず再評価する。\n脱水補正・鎮痛と外科適応の判断、災害時の画像・検査資源の配分を意識する。",
    "branchConditions": "【必須処置】\n初療開始から15分以内に必要な対応を選択\n・モニター装着\n・末梢ルート確保\n・急速輸液\n・鎮痛\n・外科\n・消化器科\n・放射線科\n【対応できた場合】\n腹痛・脱水が改善し、画像評価後に入院調整へ\n【一つでも対応できなかった場合】\n腹膜刺激徴候・頻脈増悪が出現し、急性腹症が進行",
    "postErSetting": "EU入院後、腹部所見・バイタルを経時的に観察し、外科と連携する。腹膜炎徴候が出現した場合は手術適応を再評価する。",
    "moulage": "",
    "originalId": "34",
    "originalCase": "[\"https://app.notion.com/d6cbd3b240ba437da0dd6b9ecd37da67\"]"
  },
  {
    "id": 40,
    "notionPageId": "043f4f74-5f4f-441b-9107-b88b036518d3",
    "name": "肝損傷",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:51",
    "method": "救急車",
    "expectedTriage": "赤",
    "clinicalZones": "[\"救外\"]",
    "destination": "[\"ICU\"]",
    "opeAg": "[\"OPE\",\"AG\"]",
    "overview": "救急車第3波。体幹部外傷による腹腔内出血疑いとして搬入。張碓付近のマイクロバス多重衝突で、前方座席またはシートベルトに体幹部を強打。右側腹部痛、FAST陽性、肝損傷。AG室でTAEを行うが、TAE後に再出血して循環が不安定となり、緊急開腹によるダメージコントロール手術ののちICU入室。",
    "chiefComplaint": "右側腹部痛",
    "rescueVitals": "HR 125、BP 78/50、SpO2 94%RA、RR 30",
    "primaryTriageFindings": "右側腹部痛、低血圧、頻脈、右側腹部圧痛・筋性防御",
    "initialVitals": "HR 125、BP 78/50、SpO2 94%RA、RR 30",
    "exam": "右側腹部に圧痛・筋性防御、顔面やや蒼白。",
    "tests": "FAST: モリソン窩陽性。造影CT: 肝損傷、腹腔内出血。",
    "bloodGas": "〇",
    "specimenTests": "〇",
    "imaging": "〇",
    "treatment": "輸液・輸血、肝損傷に対するTAE（AG）による止血。",
    "additionalEvent": "症例35と同時搬入。救外での輸血・AG室調整と、手術室・ICUの資源状況確認を促す。",
    "controllerInstruction": "FAST陽性を提示し、造影CT／止血治療の優先順位判断とAG室へのTAE依頼を促す。",
    "controllerChecklist": "□ FASTを実施し陽性所見をチームで共有したか\n□ 輸液・輸血への反応（responder／transient／non-responder）を分類したか\n□ 血行動態からCT室へ運べるかを判断したか\n□ AG室へTAEを依頼したか",
    "actingPoints": "右上腹部を強く押さえ、前傾姿勢でぐったり。体動や触診で激痛。",
    "focus": "FAST陽性、肝損傷、輸液・輸血、TAE、AG室調整",
    "learningPoints": "鈍的腹部外傷＋FAST陽性（モリソン窩）＋ショックでは、輸液・輸血への反応性で方針が分かれる。\n安定化すれば造影CT→TAEなどの非手術的管理、反応不良なら緊急開腹止血を躊躇しない。",
    "branchConditions": "【必須処置】\n初療開始から15分以内に必要な対応を選択\n・モニター装着\n・末梢ルート確保\n・急速輸液\n・輸血\n・外科\n・放射線科\n・手術室/麻酔科\n【対応できた場合】\n血圧・Hbを維持し、放射線科へ搬送\n【一つでも対応できなかった場合】\n血圧・Hbが低下し、緊急手術による止血へ切り替え",
    "postErSetting": "AG室でTAE後、BP 76/48・HR 135、Hb 6.8、腹部膨満、FASTで腹腔内液体増加を呈し再出血する。手術室へ搬送して緊急開腹ダメージコントロール手術（ガーゼパッキング）を行い、術後はICU管理とする。",
    "moulage": "",
    "originalId": "102",
    "originalCase": "[\"https://app.notion.com/1a519c8782c049f585dbd9332144f706\"]"
  },
  {
    "id": 41,
    "notionPageId": "5a4d22ba-0168-4e92-8e62-b2c1f759095a",
    "name": "大腿骨骨折＋脂肪塞栓症候群",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:55",
    "method": "乗用車",
    "expectedTriage": "黄",
    "clinicalZones": "[\"救外\"]",
    "destination": "[\"ICU\"]",
    "opeAg": "",
    "overview": "乗用車6。歩行不能の黄として受け入れ後、二次トリアージ中に呼吸状態が悪化する。張碓付近の多重衝突事故で右大腿部を強打し歩行不可。二次トリアージ中に会話困難、呼吸促迫、意識低下。大腿骨骨折に伴う脂肪塞栓症候群。挿管・人工呼吸後もP/F比 55と酸素化が改善せず、ECMO導入の可能性を含めICU管理となる。",
    "chiefComplaint": "大腿部痛・歩行不能",
    "rescueVitals": "",
    "primaryTriageFindings": "歩行: 歩行不能のため黄。呼吸: 初期は見たまま、その後SpO2 80%RAを付与。循環: 初期HR 100、BP 120/70。意識: 初期は指示に従えるが、二次で突然ぐったりし意識低下",
    "initialVitals": "初期: BP 120/70、HR 100、SpO2 96%RA",
    "exam": "右大腿部の腫脹と圧痛、大腿中央部変形、患肢短縮と外旋位。",
    "tests": "X線: 大腿骨骨幹部骨折。胸部X線・CT: 両肺びまん性のすりガラス〜snow storm様陰影。血液ガス: PaO2 55mmHg（FiO2 1.0）でP/F比 55。血小板低下、Hb低下。MRI: 脂肪塞栓症候群。",
    "bloodGas": "〇",
    "specimenTests": "〇",
    "imaging": "〇",
    "treatment": "骨折固定、酸素投与、気管挿管・人工呼吸管理（肺保護換気・高PEEP）。",
    "additionalEvent": "乗用車6で来院。同乗の症例45（胸部症状）と同時に受付となる。軽症ゾーン混雑時に発生させ、再評価能力を確認する。挿管・人工呼吸後も酸素化が改善しない設定とし、ECMO導入の可能性ありとしてICU・臨床工学技士へ準備を依頼させる。",
    "controllerInstruction": "初期は大腿骨骨折として提示。途中でSpO2 80%、意識低下、点状出血を付与し救外移動を促す。挿管・人工呼吸後もPaO2 55mmHg（FiO2 1.0）＝P/F比 55と提示し、ECMO導入の可能性を含むICU入室と臨床工学技士の招集、骨接合術の延期を判断させる。",
    "controllerChecklist": "□ 二次トリアージ中のSpO2低下・意識変容を捉えたか\n□ 点状出血を含む三徴を確認し赤へトリアージアップしたか\n□ 大腿骨骨折を早期に固定したか\n□ 気管挿管・肺保護換気（高PEEP）へ移行したか\n□ P/F比55の高度低酸素を共有し、ECMO準備をICU・臨床工学技士へ依頼したか\n□ 骨接合術の延期とICU入室を調整したか",
    "actingPoints": "一次〜二次までは右大腿を痛がる。二次からJCS20まで悪化し、呼吸を荒くする。酸素後も意識は悪いまま。挿管以降は反応を返さず、コントローラーの数値提示で進行する（演技不要）。",
    "focus": "二次トリアージ中の急変、脂肪塞栓症候群、重症呼吸不全（P/F 55）、ECMO準備調整、ICU入室調整",
    "learningPoints": "長管骨骨折後12〜72時間に、呼吸障害・意識障害・点状出血の三徴で脂肪塞栓症候群を発症しうる。\n早期の骨折固定が予防に有効で、経過観察中の急変（SpO2低下）を捉える再評価が重要。\n人工呼吸管理のみならEUだが、P/F比が極端に低くECMO候補となる例は絶対的ICU適応であり、回路・臨床工学技士の資源調整が要る。",
    "branchConditions": "【必須処置】\n初療開始から15分以内に必要な対応を選択\n・モニター装着\n・酸素投与\n・気道確保・挿管\n・骨折部の固定\n・整形外科\n・ICU\n【対応できた場合】\n酸素化・意識が安定し、ICUへ搬送\n【一つでも対応できなかった場合】\n低酸素・意識障害が進行し、ARDS様呼吸不全へ悪化",
    "postErSetting": "ICU入室後は肺保護換気・高PEEPで管理する。P/F比55の重症低酸素が持続する場合はECMO導入を検討し、臨床工学技士を招集する。骨接合術は全身状態安定後まで延期する。",
    "moulage": "",
    "originalId": "110",
    "originalCase": "[\"https://app.notion.com/aac069f9199e4745a2fd7099a492ac65\"]"
  },
  {
    "id": 42,
    "notionPageId": "60a654f1-1a50-4585-89eb-7d636cf7ee13",
    "name": "軽い腹痛",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:55",
    "method": "徒歩",
    "expectedTriage": "緑",
    "clinicalZones": "[\"軽症\"]",
    "destination": "[\"帰宅\"]",
    "opeAg": "",
    "overview": "避難ストレスによる軽い腹痛として、乗用車来院が重なる時間帯に投入。軽い腹痛、重症所見なし。",
    "chiefComplaint": "軽い腹痛",
    "rescueVitals": "",
    "primaryTriageFindings": "Walk-in。歩行: 可能。呼吸・脈拍・意識: すべて見たまま安定、指示に従える",
    "initialVitals": "実測値で安定",
    "exam": "腹部軟、反跳痛なし。",
    "tests": "必要時採血異常なし。",
    "bloodGas": "",
    "specimenTests": "",
    "imaging": "",
    "treatment": "経過観察",
    "additionalEvent": "症例39（急性腹症疑い）との重症度比較に使う。",
    "controllerInstruction": "腹部軟、反跳痛なし、バイタル安定を提示。経過観察後に帰宅可能とする。",
    "controllerChecklist": "□ 腹部所見（腹部軟、反跳痛なし）を確認したか\n□ バイタル安定を確認したか\n□ 過剰な検査を避けて経過観察としたか\n□ 増悪時の再受診を説明し帰宅導線に乗せたか",
    "actingPoints": "普通に会話可能。\n【Walk-in・軽症】必須処置をしないまま帰宅を促された場合は、「症状が強くて帰られない」「必要な処置をしてください」と訴え、必須処置が終わるまで帰宅しないことをアピールする。",
    "focus": "軽症腹痛、腹部所見確認、帰宅判断",
    "learningPoints": "",
    "branchConditions": "【必須処置】\n時間制限なし。以下を完了\n・モニター装着\n【対応できた場合】\n必須処置を完了し、症状が軽減して帰宅\n【一つでも対応できなかった場合】\n症状が強く残り、患者が「なんとかしてください」と訴える",
    "postErSetting": "",
    "moulage": "",
    "originalId": "63",
    "originalCase": "[\"https://app.notion.com/abc4b1f7ef4b4aa2843e8808b88bcb6d\"]"
  },
  {
    "id": 43,
    "notionPageId": "0ce76188-d6e7-4e8b-912d-a96d321f52e7",
    "name": "眼の異物感",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:55",
    "method": "徒歩",
    "expectedTriage": "緑",
    "clinicalZones": "[\"軽症\"]",
    "destination": "[\"帰宅\"]",
    "opeAg": "",
    "overview": "粉塵による眼の異物感として投入。粉塵による眼の異物感。",
    "chiefComplaint": "眼の異物感",
    "rescueVitals": "",
    "primaryTriageFindings": "Walk-in。歩行: 可能。呼吸・脈拍・意識: すべて見たまま安定、指示に従える",
    "initialVitals": "実測値で安定",
    "exam": "結膜充血軽度。",
    "tests": "角膜損傷なし。",
    "bloodGas": "",
    "specimenTests": "",
    "imaging": "",
    "treatment": "洗眼",
    "additionalEvent": "粉塵曝露患者を複数混ぜ、軽症ゾーン処置を確認。",
    "controllerInstruction": "視力低下なし、角膜損傷なしを提示。洗眼で改善とする。",
    "controllerChecklist": "□ 視力低下の有無を確認したか\n□ 角膜損傷・異物残存を確認したか\n□ 洗眼を実施したか\n□ 帰宅可能と判断し帰宅導線を案内したか",
    "actingPoints": "目をこする、洗眼で改善。\n【Walk-in・軽症】必須処置をしないまま帰宅を促された場合は、「症状が強くて帰られない」「必要な処置をしてください」と訴え、必須処置が終わるまで帰宅しないことをアピールする。",
    "focus": "眼異物感、洗眼、視力確認、帰宅判断",
    "learningPoints": "",
    "branchConditions": "【必須処置】\n時間制限なし。以下を完了\n・創部処置\n【対応できた場合】\n必須処置を完了し、症状が軽減して帰宅\n【一つでも対応できなかった場合】\n症状が強く残り、患者が「なんとかしてください」と訴える",
    "postErSetting": "",
    "moulage": "",
    "originalId": "65",
    "originalCase": "[\"https://app.notion.com/b7367a2400284b83851fd9e2979625d3\"]"
  },
  {
    "id": 44,
    "notionPageId": "164cd9fe-a7cc-46ff-8929-260af79d7e5a",
    "name": "肩こり・頭重感",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:55",
    "method": "徒歩",
    "expectedTriage": "緑",
    "clinicalZones": "[\"軽症\"]",
    "destination": "[\"帰宅\"]",
    "opeAg": "",
    "overview": "疲労に伴う肩こり・頭重感として投入。疲労に伴う肩こりと頭重感。",
    "chiefComplaint": "肩こり・頭重感",
    "rescueVitals": "",
    "primaryTriageFindings": "Walk-in。歩行: 可能。呼吸・脈拍・意識: すべて見たまま安定、指示に従える",
    "initialVitals": "実測値で安定",
    "exam": "項部硬直なし、麻痺なし。",
    "tests": "検査不要。",
    "bloodGas": "",
    "specimenTests": "",
    "imaging": "",
    "treatment": "休息/内服",
    "additionalEvent": "神経症状のない頭部症状として、症例3（急性硬膜外血腫）・症例24（頭部外傷・抗凝固薬内服）との重症度差を確認する。",
    "controllerInstruction": "項部硬直なし、麻痺なしを提示。休息・内服で帰宅可能とする。",
    "controllerChecklist": "□ 項部硬直・麻痺など神経所見を確認したか\n□ バイタル安定を確認したか\n□ 過剰な検査（頭部CT）を避けたか\n□ 休息・内服で帰宅と説明したか",
    "actingPoints": "疲労感を訴える。\n【Walk-in・軽症】必須処置をしないまま帰宅を促された場合は、「症状が強くて帰られない」「必要な処置をしてください」と訴え、必須処置が終わるまで帰宅しないことをアピールする。",
    "focus": "頭重感、神経所見確認、帰宅判断",
    "learningPoints": "",
    "branchConditions": "【必須処置】\n時間制限なし。以下を完了\n・鎮痛\n【対応できた場合】\n必須処置を完了し、症状が軽減して帰宅\n【一つでも対応できなかった場合】\n症状が強く残り、患者が「なんとかしてください」と訴える",
    "postErSetting": "",
    "moulage": "",
    "originalId": "69",
    "originalCase": "[\"https://app.notion.com/8503274275ed4f2592a1698b8e836143\"]"
  },
  {
    "id": 45,
    "notionPageId": "70eab2b3-a449-4c71-a97b-fd2d8f1567fe",
    "name": "完全房室ブロック合併下壁STEMI",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "10:58",
    "method": "乗用車",
    "expectedTriage": "赤",
    "clinicalZones": "[\"救外\"]",
    "destination": "[\"ICU\"]",
    "opeAg": "[\"AG\"]",
    "overview": "乗用車6で症例41とともに来院。張碓の事故現場で救助を手伝っていた際に胸部圧迫感と徐脈を発症。循環不安定症例の受け入れ判断を行う。張碓の事故後にけが人の救助を手伝っていたところ、急に胸を押さえて苦しくなり、胸部圧迫感・ふらつき・めまいを訴えた。大腿骨骨折の負傷者（症例41）とともに乗用車6で来院。完全房室ブロックを伴う下壁STEMI。ERではアトロピン・経皮ペーシングで安定化を図りカテ室へ搬送。カテ室でVFから心停止となり、CPR・除細動後にPCPS（ECPR）を導入し緊急PCIを施行、術後はICU管理。",
    "chiefComplaint": "胸部圧迫感・ふらつき",
    "rescueVitals": "",
    "primaryTriageFindings": "歩行: 歩行不能。呼吸: RR 20、SpO2 94%RA。循環: 脈拍数30、末梢冷汗あり。意識: 清明で指示に従える",
    "initialVitals": "BP 100/50、HR 30、SpO2 94%RA、RR 20",
    "exam": "著明な徐脈、冷汗、胸部圧迫感、ふらつき、めまい、心窩部圧迫感と嘔気。",
    "tests": "心電図: 完全房室ブロック、下壁STEMI。",
    "bloodGas": "〇",
    "specimenTests": "〇",
    "imaging": "",
    "treatment": "アトロピン、経皮ペーシング、カテ室への搬送。",
    "additionalEvent": "乗用車6で症例41と同時に来院。外傷重症例と内因性重症例が重なり、手術室・カテ室・ICUの調整が同時に必要となる。進行の詳細はコントローラー指示を参照。",
    "controllerInstruction": "乗用車6。救助作業中の発症として登場させる。完全房室ブロック＋下壁STEMIを提示し、アトロピン・経皮ペーシングを促す。ER内では心停止させず、カテ室搬送の判断を促す。カテ室へ出棟した時点で学生の演技を終了し、人形に交代する。カテ室は当日稼働可能とする。",
    "controllerChecklist": "□ HR30の徐脈性ショックを認識しモニタ・除細動器を準備したか\n□ アトロピン、無効時の経皮ペーシングを実施したか\n□ 下壁STEMI（右室梗塞）を疑い硝酸薬を避け輸液で前負荷を維持したか\n□ カテ室へ早期連絡し搬送を判断したか",
    "actingPoints": "ぐったりし歩行困難。心窩部圧迫感と嘔気、冷汗。経皮ペーシング時は痛みで反応。カテ室へ出棟した時点で演技は終了（ER内では心停止させない）。以降は人形に交代する。",
    "focus": "徐脈性ショック、STEMI、カテ室搬送判断、ICU調整",
    "learningPoints": "下壁STEMIは房室ブロック・徐脈を合併しやすく、右室梗塞を合併すると前負荷依存となり硝酸薬で著明な血圧低下をきたす。\n徐脈にはアトロピン→無効ならペーシング、根本治療は再灌流（PCI）でdoor-to-balloonを意識する。\n災害ストレスで内因性のACSが発生しうる。",
    "branchConditions": "【必須処置】\n初療開始から15分以内に必要な対応を選択\n・モニター装着\n・末梢ルート確保\n・急速輸液\n・アトロピン投与\n・循環器科\n【対応できた場合】\n血圧・脈拍が一時安定し、循環器科へ搬送\n【一つでも対応できなかった場合】\n徐脈・低血圧が悪化し、致死性不整脈・心停止へ進行",
    "postErSetting": "カテ室入室後にVFから心停止となる。冠動脈造影で右冠動脈近位部の完全閉塞を確認する。CPR・除細動後、PCPSを用いたECPRを導入して緊急PCIを行い、術後はICU管理とする。",
    "moulage": "",
    "originalId": "106",
    "originalCase": "[\"https://app.notion.com/6b99d44fb6c54ca6b1a7c1356b6b2c09\"]"
  },
  {
    "id": 46,
    "notionPageId": "4adc8d86-489c-4cf4-978f-2ee0c6c6e64a",
    "name": "右緊張性気胸・フレイルチェスト",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "11:01",
    "method": "救急車",
    "expectedTriage": "赤",
    "clinicalZones": "[\"救外\"]",
    "destination": "[\"EU\"]",
    "opeAg": "",
    "overview": "救急車第4波。高度呼吸不全とショックで救外へ直行。張碓付近のマイクロバス多重衝突で、右胸部を座席または車体に強打。ショック・呼吸不全で搬送。右緊張性気胸、フレイルチェスト。胸腔ドレナージと気管挿管が必要。人工呼吸管理はEUで継続する。",
    "chiefComplaint": "右胸部痛・呼吸困難",
    "rescueVitals": "JCS10、GCS 13（E3V4M6）、BP 62/35、HR 130、SpO2 88%（15L）",
    "primaryTriageFindings": "右胸部痛、高度呼吸困難、右呼吸音減弱、奇異呼吸、頸静脈怒張、顔面蒼白",
    "initialVitals": "JCS10、GCS 13（E3V4M6）、BP 62/35、HR 130、SpO2 88%（15L）",
    "exam": "皮下気腫著明、右呼吸音減弱、フレイルチェストあり。ドレーン・挿管後にSpO2改善。",
    "tests": "胸腔減圧・胸腔ドレーンで安定化後のCT: 右多発肋骨骨折、気胸。",
    "bloodGas": "〇",
    "specimenTests": "〇",
    "imaging": "〇",
    "treatment": "直ちに胸腔減圧、胸腔ドレーン、必要時に気管挿管・人工呼吸管理。循環・呼吸が安定後にCT。",
    "additionalEvent": "症例47（クラッシュ症候群）と相前後して到着。重症呼吸不全と透析候補が重なり、本部での入院先調整を促す。",
    "controllerInstruction": "右呼吸音減弱、頸静脈怒張、ショックを提示。緊張性気胸として迅速処置を促す。",
    "controllerChecklist": "□ 頸静脈怒張・右呼吸音減弱・ショックから緊張性気胸を臨床診断したか\n□ CTを待たずに胸腔減圧→胸腔ドレーンを行ったか\n□ 減圧前の陽圧換気を避けたか\n□ 循環・呼吸が安定してからCTを実施したか\n□ フレイルチェストに対し挿管・陽圧換気と鎮痛を行ったか\n□ 人工呼吸管理を継続できる入院先を本部と調整したか",
    "actingPoints": "右胸部を痛がり、ぐったりして会話はほとんどできない。",
    "focus": "緊張性気胸、胸腔ドレーン、挿管・人工呼吸管理、病床調整",
    "learningPoints": "頸静脈怒張＋呼吸音減弱＋ショックは緊張性気胸で、画像を待たず臨床診断で即時減圧する。\n奇異呼吸を伴うフレイルチェストは肺挫傷を合併し、挿管・陽圧換気と鎮痛が有効。\n陽圧換気の前提として胸腔減圧が必須である。\n手術を要さず循環が安定すれば、人工呼吸管理を継続できる病床を確保する。",
    "branchConditions": "【必須処置】\n初療開始から15分以内に必要な対応を選択\n・モニター装着\n・酸素投与\n・気道確保・挿管\n・胸腔ドレーン留置\n・鎮痛\n・心臓血管外科\n・ICU\n【対応できた場合】\n血圧・SpO2が改善し、安定後に入院先へ搬送\n【一つでも対応できなかった場合】\n血圧・SpO2がさらに低下し、心停止へ進行",
    "postErSetting": "EU入院後も気管挿管・人工呼吸管理と鎮痛を継続する。",
    "moulage": "",
    "originalId": "112",
    "originalCase": "[\"https://app.notion.com/e316d61036c045bfa2d95e28c7a218ce\"]"
  },
  {
    "id": 47,
    "notionPageId": "9ed296f2-3cde-4c82-a409-c5791118e2d7",
    "name": "クラッシュ症候群",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "11:10",
    "method": "救急車",
    "expectedTriage": "赤",
    "clinicalZones": "[\"救外\"]",
    "destination": "[\"ICU\"]",
    "opeAg": "",
    "overview": "車内閉じ込めまたは自宅倒壊による長時間圧挫後に搬送。高K血症リスクを提示。長時間右下腿圧挫後のクラッシュ症候群。高K血症。CRRT（透析）を要し、デバイス装着症例としてICU管理とする。",
    "chiefComplaint": "下腿痛・腫脹",
    "rescueVitals": "BP 110/68、HR 88、SpO2 97%RA、RR 20。",
    "primaryTriageFindings": "下腿腫脹、水疱、知覚低下、褐色尿",
    "initialVitals": "BP 110/68、HR 88、SpO2 97%RA、RR 20",
    "exam": "右下腿腫脹、知覚麻痺、足趾運動低下。",
    "tests": "血液ガスでK高値、CK高値、褐色尿。",
    "bloodGas": "〇",
    "specimenTests": "〇",
    "imaging": "",
    "treatment": "大量輸液、高カリウム補正。CRRT導入の準備とICU入室を調整する。",
    "additionalEvent": "救急車⑧で搬入し、重症患者の優先順位を確認。",
    "controllerInstruction": "下腿腫脹、褐色尿、高Kを提示。大量輸液・高K補正に加え、CRRT導入とICU入室、臨床工学技士の招集など自院内の調整を判断させる。",
    "controllerChecklist": "□ 心電図モニタを装着し高K血症の変化を監視したか\n□ 早期から大量輸液を開始したか\n□ 高K血症にカルシウム・GI療法を行ったか\n□ 褐色尿・CK高値から色素性腎症を想起し尿量を確保したか\n□ コンパートメント症候群を評価したか\n□ CRRT導入とICU入室、臨床工学技士の招集を調整したか",
    "actingPoints": "下腿のしびれ、動かせない。治療遅延でCPAへ。",
    "focus": "クラッシュ症候群、高K血症、CRRT（血液浄化）導入、ICU入室調整",
    "learningPoints": "クラッシュ症候群は圧挫解除の前後にreperfusion injuryで急変し、心電図モニタと大量輸液を先行させる。\n高K血症の心電図変化（テント状T波→QRS開大→sine wave）を認識し直ちに治療する。\n色素性腎症予防のための輸液・尿量管理と、CRRT（透析）の適応判断が重要。\n区画（コンパートメント）症候群の評価を忘れない。",
    "branchConditions": "【必須処置】\n初療開始から15分以内に必要な対応を選択\n・モニター装着\n・末梢ルート確保\n・急速輸液\n・外科\n・ICU\n【対応できた場合】\n尿量を確保し、致死性不整脈を回避してICUへ搬送\n【一つでも対応できなかった場合】\n高K血症・尿量低下が進行し、VF・心停止・AKIへ悪化",
    "postErSetting": "ICU入室後にCRRT（血液浄化）を導入し、高K血症・尿量・腎機能を継続管理する。",
    "moulage": "",
    "originalId": "5",
    "originalCase": "[\"https://app.notion.com/46663a1ab7d9482bb59f26bebc12aca4\"]"
  },
  {
    "id": 48,
    "notionPageId": "5c5e70da-7efd-47b9-b607-78a36545deea",
    "name": "シートベルト外傷（腹部）",
    "patientName": "フリー",
    "ageSex": "13歳前後/性別不問（中学生）",
    "arrival": "11:20",
    "method": "救急車",
    "expectedTriage": "緑",
    "clinicalZones": "[\"救外\"]",
    "destination": "[\"EU\"]",
    "opeAg": "",
    "overview": "救急車搬送の小児緑症例。救外ゾーンで反復評価。バスのシートベルト外傷。強い腹痛と、上肢・顔面の打撲痕あり。頻脈はあるが血圧は維持。腹部臓器損傷を念頭に救外で反復評価・経過観察し、所見増悪なら入院とする。",
    "chiefComplaint": "腹痛",
    "rescueVitals": "BP 110/70、HR 118、SpO2 98%RA、RR 22、BT 36.8。",
    "primaryTriageFindings": "歩行可だが腹痛で前屈み、シートベルト痕、頻脈。血圧は保たれる",
    "initialVitals": "BP 110/70、HR 118、SpO2 98%RA、RR 22、BT 36.8",
    "exam": "下腹部〜臍部にシートベルトサイン、腹部圧痛、上肢・顔面に打撲痕。",
    "tests": "FASTで明らかな腹腔内液貯留なし。造影CTで腸間膜・消化管損傷の有無を評価。",
    "bloodGas": "〇",
    "specimenTests": "〇",
    "imaging": "〇",
    "treatment": "救外で反復評価。腹部所見増悪時は外科コンサルのうえEU入院。",
    "additionalEvent": "時間とともに腹痛が増強（遅発性腸管・腸間膜損傷の懸念）。増悪時は入院・外科コンサル。",
    "controllerInstruction": "腹痛増強・バイタル変化を段階的に提示し、経過観察→入院の判断を促す。",
    "controllerChecklist": "□ 来院時は緑として受け入れ、救外ゾーンで反復評価したか\n□ シートベルトサインを深部臓器損傷のレッドフラッグとして共有したか\n□ FAST・造影CTで評価したか\n□ 頻脈先行の代償性ショックを認識したか\n□ 腰背部痛・下肢神経症状からChance骨折を評価したか\n□ 所見増悪時に外科コンサルトとEU入院を調整したか",
    "actingPoints": "中学生役は学生が演じる（学生演技）。腹部を押さえて痛がり、バイタルは保たれるが腹痛が増強していく。",
    "focus": "シートベルト外傷、遅発性腹部損傷、救外での反復評価",
    "learningPoints": "シートベルトサインは腸管・腸間膜損傷やChance骨折のレッドフラッグで、外表が軽くても油断しない。\n中空臓器損傷はFASTや初回CTで見逃されやすく、反復した腹部診察と再評価が重要。\n頻脈先行・血圧維持の代償性ショックを認識し、非代償化を早期に察知する。",
    "branchConditions": "【必須処置】\n初療開始から15分以内に必要な対応を選択\n・モニター装着\n・末梢ルート確保\n・外科\n・消化器科\n・放射線科\n【対応できた場合】\n腹部所見・バイタルが安定し、必要時にEUへ搬送\n【一つでも対応できなかった場合】\n腹痛増悪・腹膜刺激徴候・Hb低下・血圧低下へ悪化",
    "postErSetting": "EU入院後も腹部診察、バイタル、採血を経時的にフォローする。腹痛増悪、腹膜刺激徴候、発熱、FAST陽性転化、Hb低下、血圧低下が出現した場合は外科へ再連絡し、開腹手術を検討する。",
    "moulage": "",
    "originalId": "117",
    "originalCase": "[\"https://app.notion.com/9dd75bb2eda3403e89f77dbd7cd0b07d\"]"
  },
  {
    "id": 49,
    "notionPageId": "5cd1c717-9a7c-4ef2-a4ab-94a7601eefde",
    "name": "頸椎捻挫",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "11:20",
    "method": "徒歩",
    "expectedTriage": "緑",
    "clinicalZones": "[\"軽症\"]",
    "destination": "[\"帰宅\"]",
    "opeAg": "",
    "overview": "自宅で被災し徒歩来院。地震の揺れによる後頸部痛として最終波に投入。自宅で被災し、地震の揺れで体を強く振られた後から後頸部痛。明らかな強打はない。頸椎捻挫として経過観察。",
    "chiefComplaint": "後頸部痛",
    "rescueVitals": "",
    "primaryTriageFindings": "徒歩来院。歩行: 可能。呼吸・脈拍・意識: すべて見たまま安定、指示に従える",
    "initialVitals": "実測値",
    "exam": "後頚部〜僧帽筋の疼痛。診察所見は異常なし。",
    "tests": "頸椎レントゲンを行っても異常なし。",
    "bloodGas": "",
    "specimenTests": "",
    "imaging": "〇",
    "treatment": "鎮痛、経過観察",
    "additionalEvent": "徒歩来院の最終波。終盤の情報入力遅延と帰宅導線を確認。",
    "controllerInstruction": "激痛ではなく、神経脱落なし。頸椎レントゲン異常なしを提示し経過観察へ。",
    "controllerChecklist": "□ 神経脱落症状の有無を確認したか\n□ 頸椎レントゲンの必要性を判断したか\n□ 鎮痛と経過観察の説明を行ったか\n□ 終盤の患者情報入力と帰宅導線を確認したか",
    "actingPoints": "後頚部から右肩にかけて痛いと訴える。激痛ではない。\n【Walk-in・軽症】必須処置をしないまま帰宅を促された場合は、「症状が強くて帰られない」「必要な処置をしてください」と訴え、必須処置が終わるまで帰宅しないことをアピールする。",
    "focus": "頸椎捻挫、神経所見確認、終盤の情報入力、帰宅導線",
    "learningPoints": "",
    "branchConditions": "【必須処置】\n時間制限なし。以下を完了\n・鎮痛\n【対応できた場合】\n必須処置を完了し、症状が軽減して帰宅\n【一つでも対応できなかった場合】\n症状が強く残り、患者が「なんとかしてください」と訴える",
    "postErSetting": "",
    "moulage": "",
    "originalId": "114",
    "originalCase": "[\"https://app.notion.com/2a99b06378fb4a8eacf84d4d0a2cb53e\"]"
  },
  {
    "id": 50,
    "notionPageId": "d89b5fdd-f37e-4308-9ecd-e4bd6e0fb614",
    "name": "右下腿開放骨折",
    "patientName": "フリー",
    "ageSex": "フリー",
    "arrival": "11:30",
    "method": "救急車",
    "expectedTriage": "黄",
    "clinicalZones": "[\"救外\"]",
    "destination": "[\"EU\",\"ICU\"]",
    "opeAg": "[\"OPE\"]",
    "overview": "救急車第5波。開放骨折として搬入し、手術室逼迫下で自院の手術室調整と手術順位の判断を行う。張碓付近の多重衝突事故で、車内の座席下または変形した車体に右下腿を挟まれて受傷。右下腿開放骨折。創部から出血あり、圧迫止血中。洗浄・抗菌薬・固定のうえ手術室調整を行い、術後はEUもしくは一般病床入院。",
    "chiefComplaint": "右下腿痛・出血",
    "rescueVitals": "HR 110、BP 145/88、SpO2 95%RA、RR 20",
    "primaryTriageFindings": "右下腿約10cm開放創、骨露出、出血持続、下腿変形",
    "initialVitals": "HR 110、BP 145/88、SpO2 95%RA、RR 20",
    "exam": "右下腿に開放創、出血あり圧迫止血中、歩行不可。",
    "tests": "レントゲン: 右下腿開放骨折。",
    "bloodGas": "〇",
    "specimenTests": "〇",
    "imaging": "〇",
    "treatment": "止血・固定、緊急手術（洗浄・デブリドマン＋骨折固定）。",
    "additionalEvent": "手術室・カテーテル治療の優先順位調整が必要となる。",
    "controllerInstruction": "右下腿開放創・骨露出・出血を提示。洗浄・抗菌薬・固定のうえ、症例40・症例45など他の緊急症例との手術室優先順位調整を促す。",
    "controllerChecklist": "□ 圧迫止血を継続し出血をコントロールしたか\n□ 創部洗浄と抗菌薬投与を早期に行ったか\n□ 下腿の固定と疼痛管理を行ったか\n□ 末梢循環・神経所見を評価したか\n□ 手術室の空き状況を確認し、他の緊急手術（症例40・45等）との優先順位を調整したか\n□ 手術室と入院病床の両方を事前に確保したか",
    "actingPoints": "右下腿を見ないようにし、創部出血を心配する。わずかな振動でも激痛。手術時期を不安がる。",
    "focus": "開放骨折、止血・固定、手術室逼迫下の手術室調整・手術優先順位判断",
    "learningPoints": "開放骨折は早期の洗浄・デブリドマンと抗菌薬投与、確実な固定が基本。\n出血は圧迫止血で管理し、末梢循環・神経所見を評価する。\n手術室逼迫時は自院内で手術順位を調整し、入院病床を事前に確保する。",
    "branchConditions": "【必須処置】\n初療開始から15分以内に必要な対応を選択\n・モニター装着\n・末梢ルート確保\n・輸血\n・骨折部の固定\n・創部処置\n・外科\n・整形外科\n・手術室/麻酔科\n【対応できた場合】\n止血・創部処置・固定を行い、緊急手術へ搬送\n【一つでも対応できなかった場合】\n出血・疼痛・創部汚染が増悪し、手術調整が遅延",
    "postErSetting": "緊急手術（洗浄・デブリドマン＋骨折固定）後はEUまたは一般病床へ入院する。",
    "moulage": "",
    "originalId": "103",
    "originalCase": "[\"https://app.notion.com/e51fc6eb257641898cf0330e426c6ffc\"]"
  }
];

// Controller guidance is maintained in the linked controller handout database.
export const controllerCases: ControllerCaseRecord[] = [];
export const controllerCaseByPatientId = new Map(controllerCases.map((item) => [item.patientId, item]));

